### ISSUE TITLE
Rule suppression documentation

### ISSUE THREAD

**Issue by jrudge-kcom** [stelligent/cfn_nag#100]
Hi,

We are looking to integrate CFN Nag into our pipeline, however some of the default rules don't quite match our Cloud Formation patterns. I can see there is a suppression feature however I am unclear on how to implement it. I have added the following within the security group resource:

```JSON
      "Metadata": {
        "cfn_nag" : {
          "rules_to_supress" : [
            { "id": "F1000" }
          ]
        }
      },
```
That is based on the information here: https://github.com/stelligent/cfn_nag/blob/master/features/suppression.feature. It shows up as being processed in the debug:
```
@metadata={"cfn_nag"=>{"rules_to_supress"=>[{"id"=>"F1000"}]}}  
```
however it's not suppressed. Can you please advise how the suppression is intended to be implemented?

Best Regards,

Jonathan

**Comment by erickascic** [comment]
@jrudge-kcom Jonathan - I think you are pretty close but try changing 'supress' to 'suppress' (add a 'p')

There's a YAML based example here:
https://github.com/stelligent/cfn_nag/blob/master/spec/test_templates/yaml/security_group/sg_with_suppression.yml

**Comment by jrudge-kcom** [comment]
@erickascic Typo "D'oh!" That's working now and thanks for the link, I missed those.

Thank you!
