### ISSUE TITLE
Node Module wrapper for this great tools

### ISSUE THREAD

**Issue by abdennour** [stelligent/cfn_nag#102]
# Issue Type: Feature Request

Please consider wrapping the module as NodeJS module (npm) since the NodeJS community is huge.

**Comment by erickascic** [comment]
@abdennour question: are you interested in writing rules in js, or having the whole tool in js?  I'm considering some options for the former (to allow rules in js, ruby, python)

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/165955379
