### ISSUE TITLE
Error when I try to run this as API Gateway/Lambda integration...

### ISSUE THREAD

**Issue by aelmadho** [stelligent/cfn_nag#111]
Hello,

I am trying to get this up and running using API Gateway Lambda function execution, so I have updated the main Java handler file to point to "api_gateway_invoker.rb":

private static final String rubyFileName = "api_gateway_invoker.rb";

And  added this to the POM.xml:
```
<properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```
Then did a "mvn clean install && sls deploy --stage release --verbose" and my lambda gets executed with the error message as attached.

Is APIGateway Invoccation via Lambda supported at this point?

**Comment by aelmadho** [comment]
Attaching log file
[cfn-nag-apigatway-lambda-error.txt](https://github.com/stelligent/cfn_nag/files/1826829/cfn-nag-apigatway-lambda-error.txt)

**Comment by urezdaye** [comment]
+1 same error

**Comment by twellspring** [comment]
No response on this issue for 6+ months.  Closing.
