### ISSUE TITLE
Working with SAM templates

### ISSUE THREAD

**Issue by rastogia** [stelligent/cfn_nag#115]
While using aws sam templates currently, it fails to parse with errors like:
Unresolved logical resource ids: ["MyCustomLambdaFunction.Alias"]

Do we have any plans to upgrade it for sam templates in near future?

**Comment by erickascic** [comment]
yep, we will definitely take this on.  if you have a template that is failing to parse - can you attach it here or provide the snippet?

**Comment by rastogia** [comment]
Below is a snippet from the sam template which is causing issue:
  UserLambdaTopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref UserLambda.Alias
      Protocol: lambda
      TopicArn: !Ref UserTopic
I believe since UserLambda.Alias is not physically present in the template file (only serverless declaration of function UserLambda is present), it is throwing error while parsing.
Thanks

**Comment by jeffb4** [comment]
Created a cfn-model issue to address this: https://github.com/stelligent/cfn-model/issues/30

**Comment by rastogia** [comment]
Hi,
Sorry to bother, but just tested with the sam templates and I can still see the same error:
`$ cfn_nag -v
0.3.54

$ cfn_nag_scan --input-path wfs.yaml
------------------------------------------------------------
wfs.yaml
------------------------------------------------------------------------------------------------------------------------
| FAIL FATAL
|
| Unresolved logical resource ids: ["MyUserLambda.Alias", "MySubscribedDataLambda.Alias"]

Failures count: 1
Warnings count: 0`
Am I missing something pls?
Thanks

**Comment by erickascic** [comment]
can you provide the full template that is failing?  thanks!

**Comment by erickascic** [comment]
give 0.3.88 a go.
