### ISSUE TITLE
AWS codepipeline error

### ISSUE THREAD

**Issue by viralpatel94** [stelligent/cfn_nag#132]
I have setup a three tier CI/CD pipeline using AWS Codepipeline, I used the AWS serverless repo to deploy CFN-nag to lambda and adjusted the newly created IAM role to the permissions mentioned in the documentation, but I ended up giving fulladmin-codepipeline rights to the role.  

The source stage is an s3 bucket which contains a test.json that should be passed into the my test stage which is the cfn-nag lambda function. I am currently having problems with the function being invoked. 

![capture](https://user-images.githubusercontent.com/39914625/40923597-318d089a-67e3-11e8-884b-b2f5657ca8f9.PNG)

In codepipeline I have the following configurations for the cfn-nag lambda stage,

![image](https://user-images.githubusercontent.com/39914625/40923673-6a33e402-67e3-11e8-9c02-f7586c849225.png)

The CF template is within the pipeline-bucket-test s3 bucket under the test directory.

Could I please get assistance on why I am getting the zip error?

**Comment by erickascic** [comment]
This error indicates that the input artifact is either corrupt or not a zip in the first place.  The cfn_nag lambda will attempt to unzip the zip and look for the templates that match the "user parameters" value.
