### ISSUE TITLE
Violations: Add Line Number

### ISSUE THREAD

**Issue by ejohn20** [stelligent/cfn_nag#133]
Add support to output the line number for each violation in the results.

**Comment by erickascic** [comment]
I can probably get enough information out of the parser to know the line number of a given resource's key but.... finding out a line number for the part of a resource that is causing trouble... (for example - the line number and column for 0.0.0.0/0 in a security group) would be big trouble.  as it stands the code for a rule (that emits violations) is pretty simple and only has to understand resources at a pretty high level.  i believe the rules would have to be able to map attributes back to the underlying "code" of the template which might cause a pretty heavy "tax" on rule development unless I can come up with something generic that I don't yet see.

**Comment by ejohn20** [comment]
I think the line number identifying the resource is a great start! I'm working on a script to export the JSON to a more digestible format in CI (xUnit, etc.) that I can share with you when it's done. The line number will help CI tools dig into the exact location of the problem.

**Comment by ejohn20** [comment]
@erickascic Here's a bash script that I put together to parse the JSON results and export to xUnit / jUnit results for CI processing: https://gist.github.com/ejohn20/ffdd1dc05db0a4226137b972b9007639

Makes these results much easier to see in Jenkins.
