### ISSUE TITLE
Has anyone successfully built a AWS Codepipeline using cfn_nag?

### ISSUE THREAD

**Issue by viralpatel94** [stelligent/cfn_nag#134]
I am currently struggling with deploying this lamdba in a pipeline fashion. I have been using AWS Codepipeline and currently I am getting errors with s3 having access to the input artifact itself during my last stage when the json template goes into the cloud formation stage.

Does anyone have documentation of how to implement this using cloud formation as the final stage?

Currently, my source is an s3 bucket, which goes to a lambda stage(cfn_nag) which then goes to a cloud formation stage. Its failing after cfn_nag ok's the template and it tries to go to the stack 

![image](https://user-images.githubusercontent.com/39914625/41203019-be5b1f4e-6c9f-11e8-8815-765746e675e5.png)
But I have given full access to everything

**Comment by viralpatel94** [comment]
The problem seems to the output artifact, what/where is the output artifact supposed to be? The CFN_Nag function does not seem to be producing an output artifact for my last to use as an input

**Comment by dallinwright** [comment]
The output artifact from the codepipeline is stored an “Artifact Repository” you configure during the initial pipeline creation. If done via cloudformation it will look something like this:

      ```ArtifactStore:
        Type: S3
        Location: !Ref SiteBucketName```

Within that bucket, you can view the bucket policy JSON and see what has rights to read/write to that bucket beyond the ACL’s. You can manually specify access here to say codepipeline/lambda and see what works.

Did you also add rights to the pipeline to the lambda execution role like so? This was taken from the serverless deployment page and is required for lambda to be able to update the codepipeline with the status of a specific check, in this case the cfn_nag tool.
        ```{
            "Effect": "Allow",
            "Action": [
                "codepipeline:PutJobFailureResult",
                "codepipeline:PutJobSuccessResult"
            ],
            "Resource": "*"
        }```


The cfn_nag tool performs a check in an Invoke stage in the codepipeline and returns either a 0 for success or a non zero code for fatal errors as fas as I know.

Are you still having issues with the pipeline?

**Comment by viralpatel94** [comment]
@dallinwright I am still having issues.

I am still having issues!

I have setup a 3 tier pipeline, where the source is an s3 bucket where I am putting in zips of CF templates into and that is going into my second stage which is the cfn_nag lambda function and being analyzed there.  All this is working fine.  Where the problem is happening is in the last stage when after cfn_nag says the zip is analyzed and the templates have no problem, going into my last stage which is a deploy environment via cloud formation.

I reached out to AWS and they mentioned you cannot pass in zips into the deploy stage in codepipeline.

What I need better guidance with is, when CFN_NAG oks the json/zip file, how do I push it to my final deploy stage?

See attached for the setup and config of my last stage, I have encryption off on everything and full access for my roles

![pipeline](https://user-images.githubusercontent.com/39914625/41437188-d4b397d0-6ff1-11e8-8570-6920d497b201.PNG)
![last stage](https://user-images.githubusercontent.com/39914625/41437288-0203025c-6ff2-11e8-8385-88c4024eb4c6.PNG)

**Comment by twellspring** [comment]
@viralpatel94 I'm going through old issues and see this one never got resolved. Did you ever get this working?

**Comment by twellspring** [comment]
@viralpatel94 I am closing this issue.  If you are still having problems please either re-open or open a new issue detailing your current problems.
