### ISSUE TITLE
Will it just scan IAM policies?

### ISSUE THREAD

**Issue by zerolaser** [stelligent/cfn_nag#137]
We use terraform for creating all the IAM stuff and security groups. I was wondering if it just scans the IAM policies and security groups that are wide open ?

**Comment by erickascic** [comment]
cfn-nag is a static analysis tool.... so it's likely not going to help you with terraform.  cfn-nag will *never* talk to an AWS service endpoint to figure anything out.  it *always* just examines the cloudformation template and tries to "understand" the template without executing it.  (which is how it runs in a few seconds vs. minutes)
