### ISSUE TITLE
Add HTTP listener to centralize scan templates

### ISSUE THREAD

**Issue by bobrich** [stelligent/cfn_nag#143]
Just for your consideration.  I built a very simple HTTP listener into cfn_nag to allow me to run it in one place with a known set of rules and settings. 

https://github.com/bobrich/cfn_nag/commit/d886f38facda3e4f6c550b76f04befdce442a245

I'd do a pr but my ruby-fu is terrible so I'm just passing along the idea. :)

To post a template with curl you do something like:

curl -X POST -H "Content-Type: text/plain" --data @mytemplate.cfn localhost:4567

e.g.

```
[ec2-user@ip-10.0.0.1 ~]$curl -X POST -H "Content-Type: text/plain" --data @S3_Website_With_CloudFront_Distribution.template localhost:4567
{
  "failure_count": 0,
  "violations": [
    {
      "id": "W10",
      "type": "WARN",
      "message": "CloudFront Distribution should enable access logging",
      "logical_resource_ids": [
        "WebsiteCDN"
      ]
    },
    {
      "id": "W31",
      "type": "WARN",
      "message": "S3 Bucket likely should not have a public read acl",
      "logical_resource_ids": [
        "S3BucketForWebsiteContent"
      ]
    }
  ]

```

I haven't tested it much but it's working quite well for how little effort I put into it.

**Comment by erickascic** [comment]
It's been on my list to put out a very simple bare bones "service" for cfn_nag.  Dropping a sinatra front-end in front of cfn_nag in a docker container is probably a day or so of work.  My schedule has been tricky lately though.

In the meantime, two things you might check out to see if they are useful to you: stelligent-mu includes a plugin that calls out to cfn_nag as part of the generated pipeline, and then we've published a CodePipeline pipeline into "serverless application repository" that includes a cfn_nag lambda that you might be able to scavenge.

**Comment by bobrich** [comment]
Great to hear!  Based on my experimentation your estimate is spot on.  

Will take a look at the options you've suggested, thank you!
