### ISSUE TITLE
Ruby 2.5.x support so cfn_nag can run in Lambda

### ISSUE THREAD

**Issue by ssteo** [stelligent/cfn_nag#144]
Any chance to make cfn_nag support with Ruby 2.5.x?

I'm currently running cfn_nag in Lambda using JRuby 9.1.x but it's quite hackish.  It breaks when trying with JRuby 9.2.x where it is based on Ruby 2.5.x. Would be great if cfn_nag can support Ruby 2.5.x then we can use Lambda natively as they recently supports Ruby 2.5 runtime

**Comment by kadrach** [comment]
Admittedly I know next to nothing about Ruby, but `cfn_nag` is running quite happily on my machine.

```
% ruby --version                                            
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

About to stick this into a Lambda function as well, I'll see how I go with that.

**Comment by erickascic** [comment]
> Any chance to make cfn_nag support with Ruby 2.5.x?
> 
> I'm currently running cfn_nag in Lambda using JRuby 9.1.x but it's quite hackish. It breaks when trying with JRuby 9.2.x where it is based on Ruby 2.5.x. Would be great if cfn_nag can support Ruby 2.5.x then we can use Lambda natively as they recently supports Ruby 2.5 runtime

The problem here is more likely an issue with JRuby than anything peculiar about Ruby 2.5.  Do you have a stacktrace you can share?

**Comment by erickascic** [comment]
Going to close this one out.  Without a stack trace, hard for me to track down, and you can run "real" ruby in lambdas now, so no need for the JRuby hack

**Comment by ssteo** [comment]
Yeah, agreed. Sorry, forgotten to post an update. It works with Ruby 2.5.
