### ISSUE TITLE
Colorize output

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#146]
Adding color to the output, for example `FAIL` in ![#990000](https://placehold.it/15/99000/000000?text=+) red and `WARN` in ![#ff9933](https://placehold.it/15/ff9933/000000?text=+) yellow could help improve readability of the output and draw a reviewer's attention to particular parts.

**Comment by jesseadams** [comment]
@atkinsonm is this just for the default `cfn_nag_scan` output format of `text` ?

**Comment by atkinsonm** [comment]
@jesseadams yes, I'm using the default text output. Colorized json probably wouldn't make much sense.

**Comment by jesseadams** [comment]
@atkinsonm I agree but wanted to verify. I have this change made and working. Once I add a test or two we should be able to get this merged.

**Comment by atkinsonm** [comment]
Awesome, thanks!

**Comment by jesseadams** [comment]
@atkinsonm released in v0.4.3
