### ISSUE TITLE
Warn on resources with custom names

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#149]
Cloned from https://gitlab.com/jhctechnology/aws-cloudformation-utilities/awslint/issues/19

Custom-named resources cannot be updated when the properties require replacement. This makes it more difficult to update those resources and adds complexity to a continuous deployment model.

**Comment by erickascic** [comment]
latest cfn_nag warns on the following resource types + name properties:

'AWS::ApiGateway::ApiKey'                   => 'name',
    'AWS::CloudWatch::Alarm'                    => 'alarmName',
    'AWS::CodeDeploy::DeploymentConfig'         => 'deploymentConfigName',
    'AWS::CodeDeploy::DeploymentGroup'          => 'deploymentGroupName',
    'AWS::DynamoDB::Table'                      => 'tableName',
    'AWS::EC2::SecurityGroup'                   => 'groupName',
    'AWS::ECR::Repository'                      => 'repositoryName',
    'AWS::ElasticLoadBalancingV2::LoadBalancer' => 'name',
    'AWS::Elasticsearch::Domain'                => 'domainName',
    'AWS::IAM::Group'                           => 'groupName',
    'AWS::IAM::ManagedPolicy'                   => 'managedPolicyName',
    'AWS::IAM::Role'                            => 'roleName',
    'AWS::Kinesis::Stream'                      => 'name',
    'AWS::RDS::DBInstance'                      => 'dBInstanceIdentifier'
