### ISSUE TITLE
parameters being ignored

### ISSUE THREAD

**Issue by lucaspellucci** [stelligent/cfn_nag#154]
Hi, I am testing a few scenarios, and in two I tested (Security Groups and IAM) when the non compliant value come from the parameters file, the cfn_nag_scan does not pick it up:

Steps:
$ cfn_nag -v
0.3.55

$ cfn_nag_scan --input-path templates/sg.yaml -a parameters/sg.json
Failures count: 0
Warnings count: 0

**File sg.yaml:**
Parameters:
  Cidr:
    Type: String
    Description: Cidr
    Default: '0.0.0.0/0'

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: !Ref Cidr
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: !Ref Cidr

**File sg.json:**
[
  {
    "ParameterKey": "Cidr",
    "ParameterValue": "0.0.0.0/0"
  }
]

**If I instead hardcode the vulnerable cidr in the template, and don't use the parameter file, it works as expected:**

$ cfn_nag_scan --input-path templates/sg.yaml

WARN W5
Resources: ["InstanceSecurityGroup"]
Security Groups found with cidr open to world on egress

WARN W9
Resources: ["InstanceSecurityGroup"]
Security Groups found with ingress cidr that is not /32

WARN W2
Resources: ["InstanceSecurityGroup"]
Security Groups found with cidr open to world on ingress.  This should never be true on instance.  Permissible on ELB

Failures count: 0
Warnings count: 3

**Comment by erickascic** [comment]
Lucas, it's looking for the parameters in a specific format, otherwise it quietly ignores them (which is wrong).  So, to solve your problem in the short run, instead try:

{
"Parameters":
{
"Cidr": "0.0.0.0/0"
}
}

I'll make sure the documentation reflects this and will add some logic to raise errors on "malformed" JSON.

**Comment by erickascic** [comment]
0.3.56 includes FATAL errors if the JSON for parameters is malformed.  Also the base README.MD includes an explanation of the format (same info as in this ticket).  Thanks for finding this @lucaspellucci.

**Comment by lucaspellucci** [comment]
Thanks for looking into this @erickascic , however I think this doesn't actually solve the problem and actually create a bigger one. According to AWS doc, the correct json format to provide parameters to CloudFormation is:

[
  {
    "ParameterKey": "KeyPairName",
    "ParameterValue": "MyKey"
  }, 
  {
    "ParameterKey": "InstanceType",
    "ParameterValue": "m1.micro"
  }
]

See: https://aws.amazon.com/blogs/devops/passing-parameters-to-cloudformation-stacks-with-the-aws-cli-and-powershell/

With the change introduced by 0.3.56 , this format will generate error, and the format you suggested is not accepted by CloudFormation.

**Comment by erickascic** [comment]
Ah ok.  This JSON is never fed to CloudFormation, it's parsed by cfn_nag and substituted into the "model" of a CloudFormation template (so it's just a custom format understood by cfn_nag).  I may still have customers using this existing format, but I can enhance cfn_nag to support the format you want as well

**Comment by erickascic** [comment]
@lucaspellucci 0.3.76 should behave the way you desire
