### ISSUE TITLE
Default value for username and password on AWS::RDS::DBCluster

### ISSUE THREAD

**Issue by pmontanari** [stelligent/cfn_nag#155]
Helllo,

RDSInstanceMasterUserPasswordRule.rb and RDSInstanceMasterUsernameRule.rb is faling if a default value is provided even if NoEcho is provided.

To me, it should only return a Warning if a Default Value is set.

Thanks

**Comment by erickascic** [comment]
Patrick, the rationale behind that choice is to avoid having anything that could become a password committed to version control.  If you want to bend that rule, the workaround is to use a profile with a custom version of that rule.
