### ISSUE TITLE
Include `fail-on-warnings` option in cfn_scan

### ISSUE THREAD

**Issue by byronic** [stelligent/cfn_nag#186]
Per Eric, "we either need to add the fail-on-warning to cfn_nag_scan naively or if feeling enterprising.... figure a way to factor out the commonality of those command line scripts (and add fail-on-warning there)."

**Comment by atkinsonm** [comment]
Since the current behavior is to exit with 0/success if the results contain only warnings, introducing `--fail-on-warnings true` as the default option could be a breaking change for some users.

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/165899494
