### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#191]
A changelog would allow users to view the differences between tagged releases, which may be helpful in selecting a version or understanding the impact that upgrading a version will have.

**Comment by erickascic** [comment]
agreed.  there *was* automation to generate the issues addressed per release but looks like it's broken now after the publish.sh script was made more "beautiful".

**Comment by jeffb4** [comment]
Also, see https://keepachangelog.com/en/1.0.0/ - changelogs should not be automatically generated
