### ISSUE TITLE
Could releases include a standalone library

### ISSUE THREAD

**Issue by mneil** [stelligent/cfn_nag#198]
Not sure how great it works, and what the size of the package would be, but is it possible or even a good idea to distribute stand alone binaries for cfn_nag. I found https://github.com/pmq20/ruby-packer which claims to handle it for gems. 

I love the idea of nag, I like what it does, I dislike installing ruby just to use nag. Would love to hear thoughts on removing a ruby dependency to use the tool.

**Comment by erickascic** [comment]
there is a docker container published per release as well

**Comment by mneil** [comment]
That's helpful and I wasn't aware of that. Here's a few cases though where I'd still rather use a lighter cli tool

 - I don't do any Ruby Dev and want to validate on my Dev machine
- I want to publish an extension for an ide and not have the entire Ruby install be a pre-req
- I don't want to use a custom image as my codebuild environment
 - I'm already building a docker image and I don't want to use yours as a base because of kernel differences

Points 1 and 4 are real for me. On top of the fact we only use docker as our Dev environment and my base image isn't the same as X.

**Comment by erickascic** [comment]
well past a point - isn't it irritating to be stuck installing python for the AWS CLI? (but you pollute your system with stuff you don't want anyways to get work done)

that said - i built cfn-nag with this ruby-packer tool, and it's processed everything I've thrown at it on my Mac - so I think it's a pretty safe bet.  I don't have a convenient public place to push binaries to as of right now.... I can dig deeper if necessary on that, but the instructions to build the binary are pretty trivial on mac and linux.

brew install squashfs
curl -L http://enclose.io/rubyc/rubyc-darwin-x64.gz | gunzip > rubyc
./rubyc --gem=cfn-nag --gem-version 0.3.89 cfn_nag
