### ISSUE TITLE
Allow piping

### ISSUE THREAD

**Issue by nikolay** [stelligent/cfn_nag#20]
In some cases, the template is an output of a script, so, it would be nice to be able to just:

``` Bash
some-script | cfn_nag
```

and not have to deal with temporary files.

**Comment by Aweponken** [comment]
This would be great!

**Comment by erickascic** [comment]
version 0.1.1 supports input from stdin, or input of multiple files like:

cat foo.template | cfn-nag -r /var/lib/extra_rules

or

cfn-nag -r /var/lib/extra_rules foo.template foo2.template

the old cli interface is still available as cfn_nag_scan (to scan directories for yml/json/template)
