### ISSUE TITLE
option to flag invalid JSON?

### ISSUE THREAD

**Issue by willhallam** [stelligent/cfn_nag#203]
For some reason CFn allows JSON which is not strictly compliant when run through other tools -- for example, a template which has a trailing comma:

Valid JSON
{"List": ["one", "two", "three"] }
Invalid JSON - CloudFormation still finds acceptable and cfn_nag doesn't complain either
{"List": ["one", "two", "three",] }

This presents issues with our CI/CD pipelines, which use Python to parse the JSON, assuming it passes the cfn_nag check first.  Allowing the non-compliant JSON also presents issues when debugging with other tools, such as JSONLint, which don't like the trailing commas and throw errors which then mask other issues such as mismatched brackets, quotes, etc.

It would be great if I at least had the option to have cfn_nag flag non-compliant JSON, as it flags many other things which CFn will allow but aren't a great idea.  We can (and probably will) just add a generic JSON code scan to the pipeline in the interim, but this seems like something which could fall into cfn_nag's baliwick.

Thx

**Comment by erickascic** [comment]
There's an old issue that captures the problem here: https://github.com/stelligent/cfn-model/issues/6

I'll bump the priority since it's giving you a hard time.  Technically JSON is a subset of YAML, so cfn-model is just using a YAML parser but... it appears to let some junk through as a result...

**Comment by jesseadams** [comment]
@erickascic I think we'll want to leave the psych stuff alone in cfn-model. Perhaps we should just do a quick `JSON.parse` on the cfn-nag side before we pass the `cloudformation_string` into `audit`. We could rescue `JSON::ParserError` and increment `@total_failure_count`.

Thoughts?

**Comment by erickascic** [comment]
> @erickascic I think we'll want to leave the psych stuff alone in cfn-model. Perhaps we should just do a quick `JSON.parse` on the cfn-nag side before we pass the `cloudformation_string` into `audit`. We could rescue `JSON::ParserError` and increment `@total_failure_count`.

it definitely sounds reasonable to "preprocess" the JSON validation stuff and keep the psych parser as the one true path to generating the object model.  that said, is there a good reason not to do that preprocess in the model/parsing code?

**Comment by jesseadams** [comment]
@erickascic I could be mistaken, but I am pretty sure it is passed in to cfn-model as cloudformation text versus a path to a file (after preprocessing).

**Comment by erickascic** [comment]
Yep but can't we leave the parsing and validation down in the cfn model even if it's an extra pass (and then raise an exception on trouble)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jesseadams** [comment]
Opened https://github.com/stelligent/cfn-model/pull/51

**Comment by jesseadams** [comment]
@willhallam cfn-model 0.4.1 now flags invalid JSON by default. Please try it out and provide feedback if necessary.
