### ISSUE TITLE
Push to Docker Hub under official name

### ISSUE THREAD

**Issue by candrews** [stelligent/cfn_nag#205]
Per #188, I believe https://hub.docker.com/r/essej2003/cfn_nag/ is the test area for what will eventually be the official docker image for cfn_nag. I assume the name will be `stelligent/cfn_nag` when that happens.

I'd like for this issue to track changing to the official docker hub name.

Thanks!

**Comment by jesseadams** [comment]
@candrews thanks for reaching out! We are working out access to the stelligent dockerhub org. It is going slower than we would like. You are correct it will eventually be `stelligent/cfn_nag`.

**Comment by jesseadams** [comment]
https://cloud.docker.com/u/stelligent/repository/docker/stelligent/cfn_nag
