### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by pmontanari** [stelligent/cfn_nag#207]
Hello,

Version 0.3.93 has 2 new parameters :
  -o, --profile-path=<filename/uri>                  Path to a profile file
  -b, --blacklist-path=<filename/uri>                Path to a blacklist file

Where can I find the documentation for these features ?

Thanks
PAtrick

**Comment by erickascic** [comment]
Unfortunately only documented in commit messages.  Will add a section to the README.  In the meantime....  
The profile-path is a text file that must contain a rule identifier per line.  When t

**Comment by erickascic** [comment]
README is updated

**Comment by pmontanari** [comment]
Great thank you
