### ISSUE TITLE
F27 used for both EFS and RDS encryption

### ISSUE THREAD

**Issue by pmontanari** [stelligent/cfn_nag#208]
Hello,

Can't we use a different ruleset_id for encryption on EFS and RDS ?
lib/cfn-nag/custom_rules/EFSFileSystemEncryptedRule.rb
lib/cfn-nag/custom_rules/RDSDBInstanceStorageEncryptedRule.rb

Thanks
Patrick

**Comment by erickascic** [comment]
Indeed we can and should.  That is a bug and each rule should have its own identifier to allow proper filtering.

**Comment by erickascic** [comment]
0.3.96 released.  the RDS instance retains F27 and the EFS rule now is identified by F32
