### ISSUE TITLE
Wrong constant name boolean_base_rule (NameError)

### ISSUE THREAD

**Issue by JT-Bailey** [stelligent/cfn_nag#224]
When running `cfn_nag_scan --input-path filename.yml ` I get the error below. 
I have tried with both versions 0.4.10 and 0.4.11. I have not been able to find an answer either in this project or through Google searches. Thoughts?

Full output:
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:198:in `const_get': wrong constant name boolean_base_rule (NameError)
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:198:in `block in discover_rule_classes'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:194:in `each'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:194:in `discover_rule_classes'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:85:in `filter_rule_classes'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/custom_rule_loader.rb:55:in `execute_custom_rules'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag.rb:80:in `audit'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag.rb:58:in `block in audit_aggregate_across_files'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag.rb:55:in `each'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag.rb:55:in `audit_aggregate_across_files'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag.rb:29:in `audit_aggregate_across_files_and_render_results'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag_executor.rb:47:in `execute_aggregate_scan'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/lib/cfn-nag/cfn_nag_executor.rb:27:in `scan'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cfn-nag-0.4.10/bin/cfn_nag_scan:11:in `<top (required)>'
        from C:/Ruby26-x64/bin/cfn_nag_scan:23:in `load'
        from C:/Ruby26-x64/bin/cfn_nag_scan:23:in `<main>'

**Comment by jesseadams** [comment]
@JT-Bailey Thanks for your report. I am going to attempt to reproduce this shortly. In the meantime, you can pin to 0.4.9.

**Comment by jesseadams** [comment]
This bug is windows specific.

**Comment by jesseadams** [comment]
Reproduced on Windows 10 VM

- Worked on bash 4.4.19 with ruby 2.5.1p57
- Did not work via Command Prompt with ruby 2.5.5p157
