### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by viyh** [stelligent/cfn_nag#23]
It would be nice to have YAML template support as well as JSON.

**Comment by craigcraigcraig** [comment]
+1 For YAML support

**Comment by barnesrobert** [comment]
+1 for YAML, including the non-standard "short form" functions like `!Sub` and `!Ref`.

**Comment by elmic11111** [comment]
+1

**Comment by todscott** [comment]
+1

**Comment by erickascic** [comment]
version 0.1.1 supports YAML.  caveat emptor for a while... but it's out there for use.
