### ISSUE TITLE
cannot test custom_rules 

### ISSUE THREAD

**Issue by azam-akram** [stelligent/cfn_nag#230]
Hi
I am new to this, please accept my apology for stupid question.
I have defined my own custom rule and wrote some test cases (which executes fine). But when I test my custom rule with real cfn_nag like,
`cfn_nag -r ./lib/customized_rules/ ./spec/test_templates/s3_bucket/my_template.json`
Then I get following error
`Error: file or url for option 'rule_directory' cannot be opened: Is a directory @ rb_sysopen - ./lib/customized_rules/.
Try --help for help.`
Any help would really be appriciated.
Thanks

**Comment by erickascic** [comment]
@azam-akram are you absolutely sure that ./lib/customized_rules is a directory that exists and that you have permission to?  This error means it can't access the directory to scan for rules.

**Comment by azam-akram** [comment]
Thanks for reply. I am sure the ./lib/customised directory exists with following permissions,
 drwxr-xr-x

**Comment by jesseadams** [comment]
@azam-akram Please provide the following info:

1. Version of cfn-nag you are running
2. That operating system you are running cfn-nag on

I'll try to reproduce it. Thanks!

**Comment by azam-akram** [comment]
I am using 
cfn_version 0.4.15 
Windows OS
Git Bash terminal

**Comment by azam-akram** [comment]
When I copy my rule into 
C:\Ruby26-x64\lib\ruby\gems\2.6.0\gems\cfn-nag-0.4.15\lib\cfn-nag\custom_rules
then it works, but I want to keep my rules into a seprate directory.

**Comment by azam-akram** [comment]
Should I reinstall cfn_nag (a new version consisting of your commit)?

**Comment by azam-akram** [comment]
IT work now with cfn_nag version 0.4.16
Thanks for the fix

**Comment by jesseadams** [comment]
Thanks for confirming. Please open another issue if there is anything else we can help you with in the future.
