### ISSUE TITLE
Block any commits that do not reference an issue number

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#234]
Traceability is a good thing and then we can generate a simple release notes per release that references all issues for the commits.

for now... could probably do a client-side pre-commit hook but would be cool to see if we can block this on the server side (webhooks? actions? workflows?)

also, consider merge commits to master... the default format doesn't put the issue number first ...

**Comment by twellspring** [comment]
@erickascic Looking at this and see there are many tools out there that take well formed commit messages and turn them into release notes. But I guess we need to determine what we want in the release notes. 

I am thinking we want something like this with the issue description and issue number. 
```
0.4.21:
  Get all cfn_nag rules IDs with their related description (#250)
  Update tests for Password that are missing dynamic references (#240)
```
Is that what you are thinking on this?

**Comment by erickascic** [comment]
Well in the first place - i want the traceability between commits and GH issue numbers.  no commit should be without an issue to inform the bug or requirements around the nature of the change.  Once that is in place.... generating release notes is easier.
