### ISSUE TITLE
Disable colorize?

### ISSUE THREAD

**Issue by willhallam** [stelligent/cfn_nag#242]
So the colorized output is cool for interactive runs, but makes reviewing Jenkins logs a little problematic.  Could we get a flag to disable colorization, i.e. when running cfn_nag as part of a pipeline?

**Comment by jesseadams** [comment]
@willhallam We'll add a flag to disable soon. You can also install https://wiki.jenkins.io/display/JENKINS/AnsiColor+Plugin to alleviate issues in the meantime

**Comment by jesseadams** [comment]
@willhallam With the upcoming merge of #257 you can specify `--output_format txt` to avoid ANSI color codes in the output.
