### ISSUE TITLE
CFN-NAG in code build

### ISSUE THREAD

**Issue by rajimovij** [stelligent/cfn_nag#248]
Hi,

Can someone please advise how to implement CFN-Nag in the AWS build through buildspec and integrate it with pipeline for scanning any of the CFT template.

I tried, below spec and code build was successful, but it's not scanning the CFT that located in the code commit that was refenced in the pipeline

version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.6
pre_build:
    commands:
       - gem install cfn-nag
build:
    commands:
      - echo 'In Build'
      - cfn_nag_scan --input-path *

**Comment by erickascic** [comment]
Hi.  The --input-path argument should specify a directory where the templates are located.  If all the templates are under the current working directory for the build command.... give "cfn_nag_scan --input-path ." a try.

**Comment by twellspring** [comment]
@rajimovij Did this help? Were you able to get cfn_nag working in your pipeline?

**Comment by rajimovij** [comment]
Hi Todd,

Thank you...Yes, I made it worked with the help of forum members...

But,we are unable to post for additional questions or help in the github

Regards,
Rajesh Mohan
