### ISSUE TITLE
cfn_nag with no parameters or stdin hangs

### ISSUE THREAD

**Issue by twellspring** [stelligent/cfn_nag#249]
If the cfn_nag command is run without any parameters and without stdin, it just hangs (waiting for stdin).  Expected behavior is to print an error or show syntax.

Works as expected
```
$ aws cloudformation get-template --stack-name s3-notification-dev | cfn_nag`
$ cfn_nag iam_inline_policy_passrole_resource_wildcard_fail.yml
```

Hangs
```
$ cfn_nag
```

**Comment by Mr-Lizard** [comment]
I thought this was waiting for the user (or stdin) to provide some template source, as in the standard Unix idiom of chaining commands via stdin/stdout ?

For example:   
    
    `aws cloudformation get-template --stack-name s3-notification-dev | cfn_nag`

**Comment by twellspring** [comment]
What you wrote above works as expected.  What hangs is 
`cfn_nag`  I'll update description to be more clear.

**Comment by erickascic** [comment]
this is expected behavior.  if you type 'cfn_nag'.... feel free to type in a template and hit CTRL-D ;)
