### ISSUE TITLE
Nested stack support

### ISSUE THREAD

**Issue by lightbeard** [stelligent/cfn_nag#25]
We use [nested stacks](https://aws.amazon.com/blogs/devops/use-nested-stacks-to-create-reusable-templates-and-support-role-specialization/) exclusively. Does cfn_nag have support for nested stacks? Is there a workaround?

**Comment by erickascic** [comment]
There currently aren't any rules for checking the aggregate collection of stacks as a "gestalt", but.... you can still point cfn-nag to each individual stack in the collection.  Is there some particular item you are looking to check for?

**Comment by lightbeard** [comment]
I suppose the case would be where a template that already been executed and available in S3 is referenced. 

It turns out that after some discussion, the ability to run `cfn_nag` against all templates in a directory is sufficient for our needs. Thus, I am closing this issue.
