### ISSUE TITLE
Get all cfn_nag rules IDs with their related description

### ISSUE THREAD

**Issue by papiveron** [stelligent/cfn_nag#250]
Hello

Just wandering where  we get the list of ID inserted in cfn_nag violations with their associated message, so that one can work with them programmatically or with cloudformation through metadata, please.

Thanks a lot for the job.

Regards,
Eugène NG

**Comment by erickascic** [comment]
there is a script cfn_nag_rules included with the gem that likely gives you the information you need.  if not, let me know what's missing from the output that would help you.  also, the output of cfn_nag_rules has never been what i would call a "controlled interface" (i.e. subject to change incidentally).  if it meets your needs, would it be helpful to have this output as JSON or YAML?

**Comment by twellspring** [comment]
@papiveron did the cfn_nag_rules script help?  Would JSON/YAML be helpful for your programatic needs?

**Comment by jesseadams** [comment]
@papiveron Can you please confirm that `cfn_nag_rules` solved your need?

**Comment by twellspring** [comment]
@papiveron #269 was just merged, adding csv and json output formats to cfn_nag_rules.  This should make programatic access easier than the text output format.

**Comment by papiveron** [comment]
Hi all,

Sorry I was out of github for a relative long period and didn't follow the issue.

I'll try to work around with your answers ands suggestions and see.

Regards,
Eugène NG
