### ISSUE TITLE
Create remaining Password property rules

### ISSUE THREAD

**Issue by phelewski** [stelligent/cfn_nag#253]
Add in the missing Resource/Property rules for passwords, tokens, and keys.

Current missing items:
- AWS::Amplify::App.BasicAuthConfig
  - [x] Password
- AWS::DMS::Endpoint.MongoDbSettings
  - [x] Password
- AWS::AppStream::DirectoryConfig.ServiceAccountCredentials
  - [x] AccountPassword
- AWS::OpsWorks::Stack.RdsDbInstance
  - [x] DbPassword
- AWS::Amplify::Branch.BasicAuthConfig
  - [x] Password
- AWS::IAM::User.LoginProfile
  - [x] Password
- AWS::OpsWorks::App.SslConfiguration
  - [x] PrivateKey
- AWS::OpsWorks::Stack.Source
  - [x] Password
- AWS::EMR::Cluster.KerberosAttributes
  - [x] ADDomainJoinPassword
  - [x] CrossRealmTrustPrincipalPassword
  - [x] KdcAdminPassword
- AWS::AmazonMQ::Broker.User
  - [x] Password
- AWS::KinesisFirehose::DeliveryStream.RedshiftDestinationConfiguration
  - [x] Password
- AWS::OpsWorks::App.Source
  - [x] Password
- AWS::KinesisFirehose::DeliveryStream.SplunkDestinationConfiguration
  - [x] HECToken
- ~~Alexa::ASK::Skill.AuthenticationConfiguration~~
  - ~~[ ] ClientSecret~~ Save this for another issue as it doesn't follow the `AWS::` format
- ~~Alexa::ASK::Skill.AuthenticationConfiguration~~
  - ~~[ ] RefreshToken~~ Save this for another issue as it doesn't follow the `AWS::` format
- AWS::CodePipeline::Webhook.WebhookAuthConfiguration
  - [x] SecretToken
- AWS::Amplify::App
  - [x] OauthToken
  - [x] AccessToken
- ~~AWS::CloudFormation::CustomResource~~
  - ~~[ ] ServiceToken~~ Not a secured value
- AWS::Pinpoint::APNSChannel
  - [x] TokenKey
  - [x] PrivateKey
- AWS::Pinpoint::APNSSandboxChannel
  - [x] TokenKey
  - [x] PrivateKey
- AWS::ElastiCache::ReplicationGroup
  - [x] AuthToken
- AWS::Pinpoint::APNSVoipSandboxChannel
  - [x] TokenKey
  - [x] PrivateKey
- AWS::Pinpoint::APNSVoipChannel
  - [x] TokenKey
  - [x] PrivateKey
- AWS::Lambda::Permission
  - [x] EventSourceToken
- AWS::OpsWorks::App.SslConfiguration
  - [x] PrivateKey
----
Extras added from https://github.com/stelligent/cfn_nag/issues/253#issuecomment-551380848
- AWS::ManagedBlockchain::Member.MemberFabricConfiguration
  - [x] AdminPassword
- AWS::DocDB::DBCluster
  - [x] MasterUserPassword
- AWS::MediaLive::Channel.OutputDestinationSettings
  - [x] PasswordParam
- AWS::MediaLive::Input.InputSourceRequest
  - [x] PasswordParam

**Comment by erickascic** [comment]
don't add a rule for AWS::CloudFormation::CustomResource/ServiceToken.  that "token" is just a phone number for the lambda to invoke, not a credential

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/pull/1181

**`AdminPassword`**:

[AWS::ManagedBlockchain::Member.MemberFabricConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-managedblockchain-member-memberfabricconfiguration.html)

**`MasterUserPassword`**:

[AWS::DocDB::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html)

[AWS::Redshift::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html)

[AWS::RDS::DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html)

[AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html)

**`PasswordParam`**:

[AWS::MediaLive::Channel.OutputDestinationSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-channel-outputdestinationsettings.html)

[AWS::MediaLive::Input.InputSourceRequest](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-input-inputsourcerequest.html)

**Comment by erickascic** [comment]
> [aws-cloudformation/cfn-python-lint#1181](https://github.com/aws-cloudformation/cfn-python-lint/pull/1181)
> 
> **`AdminPassword`**:
> 
> [AWS::ManagedBlockchain::Member.MemberFabricConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-managedblockchain-member-memberfabricconfiguration.html)
> 
> **`MasterUserPassword`**:
> 
> [AWS::DocDB::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html)
> 
> * [x]  [AWS::Redshift::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html)
> * [x]  [AWS::RDS::DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html)
> * [x]  [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html)
> 
> **`PasswordParam`**:
> 
> [AWS::MediaLive::Channel.OutputDestinationSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-channel-outputdestinationsettings.html)
> 
> [AWS::MediaLive::Input.InputSourceRequest](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-input-inputsourcerequest.html)

it's my belief that the media live PasswordParams are actually SSM key names - so not sensitive

**Comment by erickascic** [comment]
pieces of this were released over time, but 0.4.72 includes all of them
