### ISSUE TITLE
Cross-stack referencing of GroupId throws error

### ISSUE THREAD

**Issue by eomaza** [stelligent/cfn_nag#26]
/lib/model/cfn_model.rb:70:in `resolve_group_id': GroupId only legal att on security group resource (RuntimeError)

Can cfn-nag handle cross-stack referencing?

**Comment by erickascic** [comment]
@eomaza, sorry for the late reply.  if you can send me a template that is giving cfn-nag convulsions, i have some time now to update things.

**Comment by erickascic** [comment]
I was able to reproduce this exception with a call to a nested stack's output like such:

"GroupId": { "Fn::GetAtt": ["NestedGuy", "Outputs.sg2output"] },

This is fixed in 0.1.7 (where it just safely ignores this since the reference is to an external value we  don't have access to)
