### ISSUE TITLE
validate ami and ec2 keypairs

### ISSUE THREAD

**Issue by networkpadawan** [stelligent/cfn_nag#260]
Hi,

is it possible to create a rule that complies to a given list (dynamodb, others) of AMI´s and keypairs?

we have a list of golden amis pre approved and would like to enforce only those.

thanks in advance

**Comment by erickascic** [comment]
It's entirely possible - rules are ultimately code, so you could develop a rule to retrieve the list from a persistent data source of your choice.

That said, cfn_nag doesn't give you any help as far referencing persistent data sources or juggling credentials and the like.  

Another issue you will run into is that AMIs tend to be parameterized within a template.  You can specify a JSON file with parameter values during analysis, but it's an extra step.

**Comment by networkpadawan** [comment]
for what i understand on your comment, do you think this is something better done outside of cfn nag? something like aws config or the like?

**Comment by erickascic** [comment]
I think that's a fair statement.  For items that are heavily parameterized and dynamic (like AMIs), cfn_nag is not going to be as useful vs. trying to detect a violation against a live resource.

**Comment by twellspring** [comment]
@networkpadawan do you have any further questions on this topic, or can we close this issue?
