### ISSUE TITLE
Update stelligent/homebrew-tap as part of publish script

### ISSUE THREAD

**Issue by twellspring** [stelligent/cfn_nag#268]
When the cfn_nag homebrew script runs, update the homebrew definition with the new release.  

stelligent/homebrew-tap/Formula/cfn-nag.rb

**Comment by Mr-Lizard** [comment]
I presume the homebrew script is started when a tag is added to the cfn_nag repository ?

**Comment by Mr-Lizard** [comment]
Well done pshelby !
