### ISSUE TITLE
Issue Running cfn-nag 

### ISSUE THREAD

**Issue by djmrr** [stelligent/cfn_nag#271]
Hey there,

Huge shout out to having such a rad tool that everyone in this community works hard to put together and support; I really dig it!
Lately I've been having an issue on- 
macOS Mojave version: 10.14.5, 
with Ruby version:
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

On any release of cfn-nag above 0.4.16.

I've been seeing this error:

```
cfn_nag_scan -r ~/Projects/cfn_nag_xxx_custom_rules -i ~/Projects/specialproject/infrastructure/template.yaml -n -o json
Traceback (most recent call last):
        21: from /Users/first.last/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
        20: from /Users/first.last/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
        19: from /Users/first.last/.rvm/gems/ruby-2.5.3/bin/cfn_nag_scan:23:in `<main>'
        18: from /Users/first.last/.rvm/gems/ruby-2.5.3/bin/cfn_nag_scan:23:in `load'
        17: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/bin/cfn_nag_scan:11:in `<top (required)>'
        16: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag_executor.rb:27:in `scan'
        15: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag_executor.rb:47:in `execute_aggregate_scan'
        14: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag.rb:29:in `audit_aggregate_across_files_and_render_results'
        13: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag.rb:55:in `audit_aggregate_across_files'
        12: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag.rb:55:in `each'
        11: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag.rb:58:in `block in audit_aggregate_across_files'
        10: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/cfn_nag.rb:80:in `audit'
         9: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/custom_rule_loader.rb:55:in `execute_custom_rules'
         8: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/custom_rule_loader.rb:85:in `filter_rule_classes'
         7: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/custom_rule_loader.rb:196:in `discover_rule_classes'
         6: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/custom_rule_loader.rb:196:in `each'
         5: from /Users/first.last/.rvm/gems/ruby-2.5.3/gems/cfn-nag-0.4.17/lib/cfn-nag/custom_rule_loader.rb:197:in `block in discover_rule_classes'
         4: from /Users/first.last/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /Users/first.last/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /Users/first.last/Projects/cfn_nag_xxx_custom_rules/RDSDBClusterMasterUserPasswordCustomRule.rb:4:in `<top (required)>'
         1: from /Users/first.last/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/first.last/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cfn-nag/util/enforce_noecho_parameter.rb (LoadError)

```

And also same error continually gets triggered with any other CLI options, like when trying to specify a specific "paramters.json" file of sorts for it to leverage in parsing for more dynamic cloudformation.

Is there a potential that I need upgrade my version of Ruby?  Maybe to 2.6.3? 

Any input and thoughts would be awesome!
Thank y'all!

-michael

**Comment by erickascic** [comment]
Hey @djmrr glad to hear the tool is useful for you.

Unfortunately, the referenced file enforce_noecho_parameter.rb was removed in 0.4.17.  It looks like you have a custom rule referencing it?  We recently added and enhanced a number of rules around verifying usernames and passwords of various database resources aren't in plaintext.  The "dynamic references" syntax for accessing values in ssm necessitated some changes.  If you had a custom rule for this, I'd suggest checking whether one of these core rules can meet your  requirements.  If you still need to maintain your custom rule, please check out the following code:

https://github.com/stelligent/cfn_nag/blob/master/lib/cfn-nag/custom_rules/password_base_rule.rb

It's a base class we use for all the common code necessary to verify sensitive resource properties.

Also, note to self, we haven't been explicit about controlled interfaces vs. "this code is subject to change".  I'll add something in the developer guide about this.
