### ISSUE TITLE
New rule to warn on ipProtocol -1

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#273]
Setting `IpProtocol: '-1'` can produce unexpected results. Per the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html#cfn-ec2-security-group-rule-ipprotocol), when `-1` is used, `ToPort` and `FromPort` are essentially ignored and access is granted on all ports from all protocols.

I believe this configuration should be treated the same as W27 and throw a warning for port ranges instead of single ports.

Credit to @grolston for the original find.

**Comment by twellspring** [comment]
@atkinsonm Thanks for the input. Yes having a warning for this makes sense.

**Comment by Mr-Lizard** [comment]
I have to ask - what is meant by a 'dangling' egress/ingress ?

**Comment by Mr-Lizard** [comment]
created PR for this - [# 279](https://github.com/stelligent/cfn_nag/pull/279)

**Comment by erickascic** [comment]
> I have to ask - what is meant by a 'dangling' egress/ingress ?

the egress/ingress is "dangling" if there is a resource for an ingress or egress in a given cfn template, but the security group it attaches to is NOT in the same template.  for example template1 could define a security group.  the template2 could accept an sg-id as a Parameter and create an egress/ingress rule using that sg-id.

**Comment by Mr-Lizard** [comment]
Thanks, I couldn't find a definition anywhere for that.

**Comment by atkinsonm** [comment]
Thanks all!
