### ISSUE TITLE
Want to run cfn_nag scan without failures

### ISSUE THREAD

**Issue by sreddi620** [stelligent/cfn_nag#277]
I would like to run the CFN-NAG scan and like to identify the vulnerabilities but i don't want my build to fail. Like i want all the vulnerabilities to be warning only or else even though if any failures occurs, it should show the message but it should not stop the codepipeline

**Comment by erickascic** [comment]
If you are running from bash or a similar *nix shell, you can just swallow the exit code.

cfn_nag_scan .... || true

Or in bash you can specify "set +e" first to disable exiting on failure.

There's no command line argument from cfn_nag_scan to mess with the exit code, but if the above doesn't solve your problem, let me know and I can give you a code snippet for a CLI that will call the backend and _not_ return an exit/error code.

**Comment by sreddi620** [comment]
Hi Eric,

This worked like a charm.
We have one more requirement. As you have explained, we can bypass all the
failure notices without build fail. However if we want to fail the build
for particular conditions like 0.0.0.0/0 ingress subnet or full permissions
for IAM user, is there any solution for this?
My request might be tough but we don't all the conditions defined in
CFN-NAG to be failed. Only few fail conditions matches our requirements.

On the same day after your reply, i tried updating in github, but i am not
able to update there. So sorry for delayed reply.
If you have time can you please review the custom rules we have prepared
for our organization and uploaded at
https://github.com/sreddi620/CFN_NAG_Rules.

Thanks,
Satish

**Comment by erickascic** [comment]
@sreddi620 if you only want to apply particular rules, then you should use a "profile".   Check out: https://github.com/stelligent/cfn_nag#profiles

(and profiles will work with your custom rules as well)

**Comment by sreddi620** [comment]
Can you please let me know how can I specify this profile path file to
buildspec file in AWS build environment.

**Comment by erickascic** [comment]
@sreddi620 the whitelist.txt file in your repository has the proper format for a "profile".  if you want *only* those rules to be applied, then the command line is cfn-nag --profile-path whitelist.txt (or wherever the whitelist.txt is stored).  cfn_nag_scan has the same (long) argument name.
