### ISSUE TITLE
Create rule for S3  Bucket Encryption

### ISSUE THREAD

**Issue by twellspring** [stelligent/cfn_nag#278]
Best Practices say that S3 buckets should be encrypted.

**Comment by Mr-Lizard** [comment]
The interesting thing is...there is no actual way to confirm this.  We have
to just
take Amazon's word at it.

**Comment by erickascic** [comment]
More specifically, this issue is around:

AWS::S3::Bucket ServerSideEncryptionByDefault
?

**Comment by Mr-Lizard** [comment]
Yes.

**Comment by Mr-Lizard** [comment]
PR created - [https://github.com/stelligent/cfn_nag/pull/282](url)
