### ISSUE TITLE
cfn-nag installation procedure from github source repo

### ISSUE THREAD

**Issue by sreddi620** [stelligent/cfn_nag#281]
Hi,

Is there any alternative command to install cfn-nag instead of installing it from gem repository.
Alternative bash command for "gem install cfn-nag". Command to install cfn-nag from "https://github.com/stelligent/cfn_nag.git" reposity directly.

**Comment by twellspring** [comment]
You can install it from the git repo directly using the *Local Install* steps in the Readme.  This creates a local gem from the git repo and then installs it.

**Comment by sreddi620** [comment]
Can you be more specific.
I want to fork the can-nag git and want to edit rules as per my
requirements and would like to use that git to run scan in my ci/cd
pipeline.
I want to install using can-nag using the fit I forked.

**Comment by erickascic** [comment]
@sreddi620 you can use the core cfn-nag with your custom rules unless you need to make changes to the core cfn-nag engine (via the --rule-directory option).  if you actually need to make changes in the core, i'd be interested to hear what they are and see if we can accommodate them so you don't have to fork.

If you cannot install Ruby for some reason, there are a few options available:
1. you can run it in a docker container: https://hub.docker.com/r/stelligent/cfn_nag
2. you can install via brew (gem)
3. you can use ruby-packer to create an executable: https://github.com/pmq20/ruby-packer

If you want to build cfn_nag yourself, scripts/publish.sh contains all the logic necessary to build.  You'd need to edit the cfn-nag.gemspec file to have the version you want, then call " gem build cfn-nag.gemspec" and then call "gem install cfn-nag-xxxx.gem" to actually install and use it.

**Comment by sreddi620** [comment]
Thanks for the info. I am able to install this report locally

**Comment by sreddi620** [comment]
I am able to install this repo locally
