### ISSUE TITLE
Cfn_nag_rules might be broken

### ISSUE THREAD

**Issue by Mr-Lizard** [stelligent/cfn_nag#283]
My apologies if this is in error, but from what I can see, cfn_nag_rules isn't reporting the correct information.

From a fresh pull:  

<img width="955" alt="Screen Shot 2019-08-17 at 12 15 47 AM" src="https://user-images.githubusercontent.com/11722105/63206958-3a6dc800-c084-11e9-89ab-0f14882e9f32.png">

You can see 'W38'  is in between 'F37' and 'F38'.  A couple of the recent additions (such as  'W42') aren't showing up either.

This is likely my fault, being unfamiliar with cfn_nag_rules, I assumed that all the information needed would be in the rule's class definition.

**Comment by erickascic** [comment]
@Mr-Lizard which version are you running against?  I don't see this behavior with 0.4.38 (and you are correct that the rule class provides all the necessary information for cfn_nag_rules to do its thing)

**Comment by Mr-Lizard** [comment]
cfn_nag -v reports...0.4.38.  However cfn_nag_rules reports...0.0.01 - Hmmmm !  

I was running against an outdated rbenv shim  :(

Thank you for your help tonight!

**Comment by erickascic** [comment]
sure thing - thanks for contributing to cfn_nag and making it better
