### ISSUE TITLE
What is the licence for the artworks?

### ISSUE THREAD

**Issue by jeshan** [stelligent/cfn_nag#288]
I understand the source code is MIT-licensed. I don't see a specific licence for the logo.
If we want to include the logo on a website, what terms should we be respecting?

**Comment by oshaughnessy** [comment]
Hi, Jeshan. Thanks for asking! We're double-checking before we answer just to be sure we've got it right.

Can I ask where you'd like to use it?

**Comment by jeshan** [comment]
I'm building an unreleased proprietary product that integrates with cfn-nag. I just intend to state on the product website that "we integrate with cfn-nag for automated static analysis" (something like that). Definitely not looking to appropriate it or the like.

**Comment by jeshan** [comment]
Hey Eric, what's the resolution for
