### ISSUE TITLE
Use cfn_nag in AWS Lambda

### ISSUE THREAD

**Issue by Indhukrishna** [stelligent/cfn_nag#291]
Do we have any examples of how to use cfn_nag in Lambda? I do not want to use it from CodePipeline. I just want a simple function that will run cfn_nag for me on a template

**Comment by erickascic** [comment]
@Indhukrishna sorry for the delay.

now that AWS support Ruby in Lambda, it's just a matter of installing the cfn-nag gem and invoking the API against your template.  Code snippet follows that audits the string form of a cfn template - up to you to get the template string from somewhere like a Lambda parameter or an s3 bucket, etc.

require 'cfn-nag'
config = CfnNagConfig.new
cfn_nag = CfnNag.new(config: config)
audit_result = cfn_nag.audit(cloudformation_string: cloudformation_string)
