### ISSUE TITLE
Do you have an equivalent for Terraform?

### ISSUE THREAD

**Issue by sumitag** [stelligent/cfn_nag#297]
Do you have an equivalent for Terraform?

**Comment by erickascic** [comment]
There are a few similar products out there that aren't Stelligent.  I think terrascan is one of them.

We do have a tool that will scan Terraform code that is < 0.12.x.  It isn't necessarily as up-to-date as cfn-nag with AWS services, but it's not too far behind either: https://github.com/stelligent/config-lint
