### ISSUE TITLE
Allow Warning to return a non zero result

### ISSUE THREAD

**Issue by joaquin386** [stelligent/cfn_nag#303]
Hi

According to the documentation Warnings exit with a zero/success result making them useless (as ppl do not normally care about warnings). I propose is there could be a flag or something else for warnings to exit a non zero result though being able on a bash script to act on that return result (basically to be use in a pipeline).

Thanks

**Comment by erickascic** [comment]
@joaquin386 you can specify --fail-on-warnings on the command line to force a non-zero exit code when there are warnings

**Comment by joaquin386** [comment]
Thanks a lot for your quick answer probably has to run first the command with a --help first.
Closing case.
