### ISSUE TITLE
Getting 403 error in codebuild after adding extension to mu.yml

### ISSUE THREAD

**Issue by itlearn360** [stelligent/cfn_nag#309]
I am getting the following error
 Running command curl -sL https://github.com/stelligent/mu/releases/download/v1.5.10/mu-linux-amd64 -o /usr/bin/mu 
 
[Container] 2019/11/16 22:31:12 Running command chmod +rx /usr/bin/mu 
 
[Container] 2019/11/16 22:31:12 Running command mu -c ./mu.yml --dryrun --assume-role arn:aws:iam::002838516900:role/mu-pipeline-my-app-mu-acpt-us-east-1 --disable-iam env up acceptance || echo "Skipping update of environment" 
AccessDenied: User: arn:aws:sts::002838516900:assumed-role/mu-pipeline-myapp-ci-us-east-1/AWSCodeBuild-1cc4b85c-3960-4085-81a6-cc63d5c42c89 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::002838516900:role/mu-pipeline-my-app-mu-acpt-us-east-1

**Comment by erickascic** [comment]
@itlearn360 i'm pretty sure this problem is on the mu side of the house.  cfn_nag never interacts with AWS ever so whatever is going on, it's on the mu side of things.  i would suggest opening an issue with mu.
