### ISSUE TITLE
Create secure rules for Alexa::ASK::Skill.AuthenticationConfiguration

### ISSUE THREAD

**Issue by phelewski** [stelligent/cfn_nag#322]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ask-skill-authenticationconfiguration.html

Alexa::ASK::Skill.AuthenticationConfiguration
-  [x] ClientSecret
-  [x] RefreshToken

**Comment by phelewski** [comment]
Waiting on https://github.com/stelligent/cfn-model/pull/56 before proceeding further since currently `CfnParser` doesn't allow the `Alexa` resource type.

**Comment by erickascic** [comment]
cfn-model 0.4.9 should give you want you need.

The created class will be named AlexaASKSkill
