### ISSUE TITLE
Update logging to 2.2.x to fix "warning: constant ::Fixnum is deprecated"

### ISSUE THREAD

**Issue by Aweponken** [stelligent/cfn_nag#34]
When using Ruby 2.4, logging 2.0.0 is warning about Fixnum being deprecated.[ This has been fixed since version 2.2.x.](https://github.com/TwP/logging/commit/1fec7be6384df1ca8cbc658a471e83c829de79e9)

**Comment by erickascic** [comment]
fixed in 0.1.2
