### ISSUE TITLE
Overriding violation types on default rules

### ISSUE THREAD

**Issue by rybons** [stelligent/cfn_nag#359]
What would be the best or most supported method of changing a default (non-custom) `warning violation` to a `failing violation`? For example, what if I wanted to change the

```
W1 Specifying credentials in the template itself is probably not the safest thing
```

rule to be a failing violation. I suppose I could define my own custom rule (and perhaps ignore the default rule), or fork the project and adjust the violation type.

Is there a simpler way to achieve this that I might be missing?

**Comment by erickascic** [comment]
you have a few options depending on the desired outcome.

the --fail-on-warnings command line argument will force a non-zero exit code if there are any warnings.  if you only want a subset of warnings to cause failure, then you could use a profile and do a separate run with the --fail-on-warnings options.

if you need the Wxxx to appear as Fxxx vs just "fixing" the exit code - that's a little trickier.  you could pipe the results to something like jq to transform the results or you could indeed add a custom rule with the desired Fxx identifier.

**Comment by rybons** [comment]
@erickascic These are great options, thanks. I was not aware of the `--fail-on-warnings` flag. Combined with the profile option I think I'm all set.
