### ISSUE TITLE
Validate all AWS Resources

### ISSUE THREAD

**Issue by foobar123-del** [stelligent/cfn_nag#364]
I am writing a custom rule which checks for tags in the cfn template.
I want to check those tags in all cfn templates for all aws resources  instead of writing it for individual resources ..

Long story short with one custom rule to check tags in cfn template. i want to validate all aws resources.

**Comment by erickascic** [comment]
you can iterate over all resources in a given template to inspect tags if they are there:

cfn_model.resources.values.select { |resource| predicate(resource.tags) }

**Comment by foobar123-del** [comment]
Thank you

**Comment by foobar123-del** [comment]
Hello,
I wrote a custom rule but its not working:
require 'cfn-nag/violation'
require 'cfn-nag/custom_rules/base'

# adding custom rules here
class LambdaFunctionDashTagRule < BaseRule

  def rule_text
    'Resources does not have tags dashplatform/dashcomponent/dashbusinessservice/dashfeature set'
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'F800001'
  end


  def audit_impl(cfn_model)
      cfn_model.resources.values.each do |resource|
#     rlist = ['AWS::RDS::DBInstance']
#     rlist.each do | rtype |
#         rtype = 'AWS::RDS::DBInstance'
        rtype = resource.resource_type
        #puts rtype
        violating_instances = cfn_model.resources_by_type(rtype).select do|instance|
          validate_instance(instance) == false
        end
          #puts violating_instances
          violating_instances.map {|violating_instance| violating_instance.logical_resource_id}
      end
#     end
  end

  def validate_instance(instance)
     found = true
     tlist = []
     instance.tags.each do | tag |
        tlist << tag["Key"]
     end
     ['dashplatform', 'dashcomponent', 'dashbusinessservice', 'dashfeature'].each do |t|
#         puts t
#         puts tlist.include?(t)
        if tlist.include?(t) == false
           found = false
        end
     end
     found
  end


end

**Comment by foobar123-del** [comment]
Hello ,
I wrote a custom rule for checking tags in template but its not working.
require 'cfn-nag/violation'
require 'cfn-nag/custom_rules/base'


class LambdaFunctionDashTagRule < BaseRule

  def rule_text
    'Resources does not have tags dashplatform/dashcomponent/dashbusinessservice/dashfeature set'
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'F800001'
  end


  def audit_impl(cfn_model)
      cfn_model.resources.values.each do |resource|

        rtype = resource.resource_type
        #puts rtype
        violating_instances = cfn_model.resources_by_type(rtype).select do|instance|
          validate_instance(instance) == false
        end
       
          violating_instances.map {|violating_instance| violating_instance.logical_resource_id}
      end
  end

  def validate_instance(instance)
     found = true
     tlist = []
     instance.tags.each do | tag |
        tlist << tag["Key"]
     end
     ['dashplatform', 'dashcomponent', 'dashbusinessservice', 'dashfeature'].each do |t|

        if tlist.include?(t) == false
           found = false
        end
     end
     found
  end


end

require 'cfn-nag/violation'
require 'cfn-nag/custom_rules/base'

class LambdaFunctionDashTagRule < BaseRule

  def rule_text
    'Resources does not have tags dashplatform/dashcomponent/dashbusinessservice/dashfeature set'
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'F800001'
  end


  def audit_impl(cfn_model)
      cfn_model.resources.values.each do |resource|

        rtype = resource.resource_type
        #puts rtype
        violating_instances = cfn_model.resources_by_type(rtype).select do|instance|
          validate_instance(instance) == false
        end
   
          violating_instances.map {|violating_instance| violating_instance.logical_resource_id}
      end

  end

  def validate_instance(instance)
     found = true
     tlist = []
     instance.tags.each do | tag |
        tlist << tag["Key"]
     end
     ['dashplatform', 'dashcomponent', 'dashbusinessservice', 'dashfeature'].each do |t|

        if tlist.include?(t) == false
           found = false
        end
     end
     found
  end


end

**Comment by foobar123-del** [comment]
if i replace with "rtype = resource.resource_type" with this "AWS::Lambda::Function" its working but i want to add all resources what are in template

**Comment by erickascic** [comment]
why do you need the nested iteration?  i would presume you could do something in one pass more like:

violating_resources = cfn_model.resources.values.select do |resource|
  missing_tags?(resource)
end

**Comment by foobar123-del** [comment]
Thanks for fixing this issue.
