### ISSUE TITLE
Updated AWS Marketplace AMI?

### ISSUE THREAD

**Issue by jeffb4** [stelligent/cfn_nag#399]
The cfn_nag AMI is `0.4.47` . Is it going to be pipelined to update automatically?

**Comment by erickascic** [comment]
I would love to pipeline it automatically but the Marketplace API doesn't support much in the way of automating publishing yet (manual process).  the new catalog API is a step in the right direction but last i checked only supports data products with a promise to support other product types.   the marketplace API experience is definitely the worst i've ever had with an AWS product... almost makes workspaces look good lol.  will put in a request to get a recent 0.5.x updated though.

**Comment by erickascic** [comment]
0.5.24 has been submitted to the marketplace gods.  presuming i didn't make a mistake in filling out the form, should be up in the marketplace within a day or two
