### ISSUE TITLE
Troubleshooting Rules located in s3 Bucket

### ISSUE THREAD

**Issue by mcahill7** [stelligent/cfn_nag#400]
I have created a custom rule that is working locally and passing tests successfully, however using the new s3 functionality doesn't seem to get the rule to trigger. I see no error messages when running it, how can I troubleshoot this further? Thanks

**Comment by erickascic** [comment]
I'll release a new version with some better debug logging for the s3 repo this morning.  In the meantime, as far as troubleshooting:

1. can you paste a copy of your repository specification?
2. presuming your repo spec is good, the creds are likely not the issue as you'd see a messy exception if that was the case
3. make sure the rule file/key ends in Rule.rb
4. make sure the class name in the rule file matches the file name XRule.rb -> XRule
5. you can try knocking the cache refresh down to 1m, or just blow away the caches: /tmp/cfn_nag_*

**Comment by erickascic** [comment]
@mcahill7 0.5.23 includes debug info for loading s3 rules when you add the --debug flag to the command line

**Comment by mcahill7** [comment]
`---
    repo_class_name: S3BucketBasedRuleRepo
    repo_arguments:
      s3_bucket_name: cfn-nag-rules-fav
      prefix: /rules
      index_lifetime: 1m
      aws_profile: default`

Here is the rule: https://github.com/mcahill7/sg-testing/blob/master/rules/CustomSgRule.rb

Thanks for adding the debug flag. Looks like the rule is not being found for some reason: 
`
DEBUG  log : S3BucketBasedRuleRepo.discover_rules in cfn-nag-rules-fav, /rules
DEBUG  log : Found rule objects: []
DEBUG  log : index: []
`
Thanks for the help

**Comment by erickascic** [comment]
the object cfn-nag-rules-fav/rules/CustomSgRule.rb is confirmed to be in s3 and you can access it with the "default" aws profile?  if so.... i guess i'd rm the caches although 1m is pretty aggressive

**Comment by mcahill7** [comment]
Yes it does exist and is accessible. I'm running this in codebuild so hopefully cache shouldn't be much of an issue. I cleared it locally just incase
This worked:
`aws s3 cp s3://cfn-nag-rules-fav/rules/CustomSgRule.rb . --profile default
download: s3://cfn-nag-rules-fav/rules/CustomSgRule.rb to ./CustomSgRule.rb`

**Comment by erickascic** [comment]
hmmm... if you are running in CodeBuild, I would presume you are using an instance profile/role?  if so - don't specify the aws_profile and it will use the ambient credentials

**Comment by mcahill7** [comment]
Tried removing the profile in repo/codebuild, no changes. Uninstalled and reinstalled nag locally, cleared cache, and ran the following
`cat infrastructure/security-groups.yaml | cfn_nag --rule-repository infrastructure/s3.yaml --debug`

Still no luck 🤔

**Comment by erickascic** [comment]
is this bucket verisoned? for your ActionServiceRole.... it looks like the open-ended policy that would cover /rules doesn't include versioning actions (e.g GetObject instead of GetObject*).   i would expect a more dramatic failure but perhaps something is sitting on an error message deep down

**Comment by erickascic** [comment]
when you say it works locally - you can access the rule from the s3 bucket locally? just not from codebuild? or you loaded the rule locally off the filesystem?

**Comment by mcahill7** [comment]
My spec tests work locally. I can't access access the rule in s3 locally or in codebuild

**Comment by mcahill7** [comment]
Can you still load the rules locally from the filesystem?

**Comment by erickascic** [comment]
just realized the artifact bucket is not where you are loading rules from.... so not sure what your bucket and bucket policy look like.  if you to meet on chime, i'm available to look closer at your bucket and/or help you do some deep instrumenting.  

yes - you can still load locally.  the s3 bucket loading is to make life more convenient for use with AWS Lambda

**Comment by mcahill7** [comment]
@erickascic sent you a zoom on linkedin if you have a few

**Comment by erickascic** [comment]
Added debug messages to the logging which should have had anyways, but the underlying problems is that Bucket.object(prefix: '/rules') in the underlying SDK won't match rules/FooRule.rb, so strip the leading forward slash if it's there from now on
