### ISSUE TITLE
ec2:DescribeTags - IAM role should not allow * resource on its permissions policy

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [stelligent/cfn_nag#408]
According to https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2.html, `*` is the only possible value for Resource, when Action is ec2:DescribeTags.

I overcame this by suppressing the rule, but it's probably best if `cfn_nag` is aware of expected behaviour.

**Comment by paulo-ferraz-oliveira** [comment]
To the maintainers: is this something we should contemplate in the future? Or can we close this and assume it's not an issue?

**Comment by erickascic** [comment]
@paulo-ferraz-oliveira definitely something i'd like to fix.  there is a deeper problem here that i think it already in the backlog around being smarter about complaining about (necessary) wildcards.

**Comment by paulo-ferraz-oliveira** [comment]
I'm going to go ahead and close this, since it seems you concluded it'll be fixed, hopefully, in any case. Thanks.
