### ISSUE TITLE
Unknown Escape Character Parsing Regex

### ISSUE THREAD

**Issue by jamesrenaud** [stelligent/cfn_nag#418]
I have a Regex pattern as part of an `AWS::WAFv2::RegexPatternSet` which is failing to be parsed due to a forward slash in the string.

```
"RegularExpressionList": [
   "^app=[a-z-\\.0-9]+\/[0-9.a-z-]+;"
]
```

This produces a fatal failure:
```
| FAIL FATAL
|
| (<unknown>): found unknown escape character while parsing a quoted scalar at line 28 column 21
```

Verified this issue exists in the latest shipping `v0.5.31`

**Comment by erickascic** [comment]
@jamesrenaud it possible for you to provide the whole template, or more of it?  The following mini snippet isn't causing a fatal violation for me

{
  "Resources": {
    "Set": {
      "Type" : "AWS::WAFv2::RegexPatternSet",
      "Properties" : {
        "Name" : "Foo",
        "RegularExpressionList" : [
          "^app=[a-z-\\.0-9]+\/[0-9.a-z-]+;"
        ],
        "Scope" : "CLOUDFRONT"
      }
    }
  }
}

**Comment by jamesrenaud** [comment]
Here's the full resource snippet

```
        "AppIdRegexPattern": {
            "Type": "AWS::WAFv2::RegexPatternSet",
            "Properties": {
                "Name": "x-mitel-app-regex",
                "Description": "Handles validating an appropriate Mitel app identifier is present, and the app is provided",
                "Scope": "REGIONAL",
                "RegularExpressionList": [
                    "^app=[a-z-\\.0-9]+\/[0-9.a-z-]+;"
                ]
            }
        },
```

I can provide the whole template if this doesn't get any further - I just need to do a little genericizing before I drop it on the internet :D

**Comment by erickascic** [comment]
@jamesrenaud thx for the template.  Still not receiving an error.  I'm wondering if there is something amiss with encoding wrt ASCII v UTF8 and the my locale v yours.... we have a release coming out today that forces UTF8 on parsing.  i'd recommend giving that a go and if that doesn't work..... then i'd wonder if there is something else in the template cascading into a failure somehow

**Comment by jamesrenaud** [comment]
Sounds good, I will try the new release and if that fails I'll try to gather up a bit more info around this and update the ticket.

Thanks for investigating so quick!

**Comment by pshelby** [comment]
@jamesrenaud Thanks for the info so far!  Sorry just to clarify, I'm able to reproduce your issue with the latest source of cfn_nag, however it's happening without the escaping backslashes (which doesn't seem to be valid JSON and does not validate with CFN).  When I use the original pattern you supplied (with escaped special characters) I do not get an error.  Let me know if you can provide more details about your environment and template.

### Environment

ruby: 2.5.3
cfn-model: 0.4.23
cfn_nag: latest (equivalent to 0.5.32, however for this purpose it is functionally the same as 0.5.31)

### Working

```json
{
  "Resources": {
    "AppIdRegexPattern": {
      "Type": "AWS::WAFv2::RegexPatternSet",
      "Properties": {
        "Name": "x-mitel-app-regex",
        "Description": "Handles validating an appropriate Mitel app identifier is present, and the app is provided",
        "Scope": "REGIONAL",
        "RegularExpressionList": [
          "^app=[a-z-\\.0-9]+\/[0-9.a-z-]+;"
        ]
      }
    }
  }
}
```
```shell
cfn_nag_dev@8a62057fe5ad:/workspaces/cfn_nag$ bundle exec cfn_nag spec/test_templates/json/wafv2/wafv2_regex_pattern_set.json 
------------------------------------------------------------
spec/test_templates/json/wafv2/wafv2_regex_pattern_set.json
------------------------------------------------------------
Failures count: 0
Warnings count: 0
```
```shell
$ aws cloudformation validate-template --template-body file://spec/test_templates/json/wafv2/wafv2_regex_pattern_set.json
{
    "Parameters": []
}
```

### Failing

```json
{
  "Resources": {
    "AppIdRegexPattern": {
      "Type": "AWS::WAFv2::RegexPatternSet",
      "Properties": {
        "Name": "x-mitel-app-regex",
        "Description": "Handles validating an appropriate Mitel app identifier is present, and the app is provided",
        "Scope": "REGIONAL",
        "RegularExpressionList": [
          "^app=[a-z-\.0-9]+/[0-9.a-z-]+;"
        ]
      }
    }
  }
}
```
```shell
cfn_nag_dev@8a62057fe5ad:/workspaces/cfn_nag$ bundle exec cfn_nag spec/test_templates/json/wafv2/wafv2_regex_pattern_set_no_escapes.json
------------------------------------------------------------
spec/test_templates/json/wafv2/wafv2_regex_pattern_set_no_escapes.json
------------------------------------------------------------------------------------------------------------------------
| FAIL FATAL
|
| (<unknown>): found unknown escape character while parsing a quoted scalar at line 10 column 11

Failures count: 1
Warnings count: 0
```
```shell
$ aws cloudformation validate-template --template-body file://spec/test_templates/json/wafv2/wafv2_regex_pattern_set_no_escapes.json

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: JSON not well-formed. (line 10, column 24)
```

**Comment by jamesrenaud** [comment]
Looks like this was a Ruby issue.

I was previously running `2.5.1` - did an upgrade to `ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]` and that seems to have resolved.

Interestingly enough I run cfn-lint as well (with the VSCode plugin) and it still catches the regex as invalid, but at least the cfn-nag scan works.

Thanks for the assistance!
