### ISSUE TITLE
[Request] ElasticLoadBalancerV2AccessLoggingRule>>access_logs.s3.enabled to support Ref parmeters

### ISSUE THREAD

**Issue by pmontanari** [stelligent/cfn_nag#421]
Hi,

The access_logs.s3.enabled parameter only accepts 'true' or 'false' and no Cloudformatoin Parameters as it would raise an exception.

Could you please add this possibility so that a CFN developper can enable/disable the access log feature as a parameter ?

Thanks

**Comment by erickascic** [comment]
@pmontanari it is possible pass in values for Parameters via the command line option:

--parameter-values-path=<s>                    Path to a JSON file to pull Parameter values from

the format for the JSON file is:
   {
     "Parameters": [
       {
         "ParameterKey": "logs",
         "ParameterValue": "true"
       }
     ]
   }

once you specify the values, the parser will substitute those values into the "model" and those values will be what the rules will evaluate against
