### ISSUE TITLE
Suppress default cfn_nag checks

### ISSUE THREAD

**Issue by soansgla** [stelligent/cfn_nag#424]
Is there a way to suppress default cfn_nag checks and just execute custom checks?

Below is my code to execute cfn_nag on custom rules but I need to suppress default checks 
`cfn_nag --rule-directory /opt/custom/rules/  cfn_directory/*.* -u json`

**Comment by erickascic** [comment]
there's not a "master switch" to turn off the core checks.  what you can do is define a profile with just your custom rules - and then only those custom rules will be applied.

**Comment by soansgla** [comment]
Thanks!
