### ISSUE TITLE
KMS Key ID enforcement to specific to region

### ISSUE THREAD

**Issue by ksredd** [stelligent/cfn_nag#425]
Whenever I run cfn templates, CFN nag should allow only specific KMS KEY ID in one region. How can i implement in Ruby file.
here is my sample code. 

# frozen_string_literal: true

require 'cfn-nag/violation'
require_relative 'base'

class SqsQueueKmsMasterKeyIdRule < BaseRule
  def rule_text
    'SQS Queue should specify KmsMasterKeyId property'
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'W48'
  end

  def audit_impl(cfn_model)
    violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
      sqs_queue.kmsMasterKeyId == 'arn:aws:kms:us-east-1:7652890765440987650986400'
    end

    violating_sqs_queues.map(&:logical_resource_id)
  end
end

**Comment by ksredd** [comment]
It will be great help, if anyone through some light on this

**Comment by erickascic** [comment]
@ksredd the posted code will consider any SQS Queue with the specified kms key as a violation.  if you want any Queue _without_ that kms key - you just need to change the == to !=.

is that what you are trying to do?

**Comment by ksredd** [comment]
Thank you very much for reply.
Yes, I have tried with !=(not equal) as well but condition is not checking/working as expected.
for your better understanding here are the steps so that you can provide me better solution.
Cloudformation template:
AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Standard Queue
Parameters:
  DelaySeconds:
    Type: Number
    Default: '5'
  MaximumMessageSize:
    Type: Number
    Default: '1024'
  MessageRetentionPeriod:
    Type: Number
    Default: '500'
  ReceiveMessageWaitTimeSeconds:
    Type: Number
    Default: '0'
  UsedeadletterQueue:
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
  VisibilityTimeout:
    Type: Number
    Default: '5'
Mappings:
  NameRegion:
    us-east-1:
      Idkms: 'arn:aws:kms:us-east-1:1234567890:key/1234567890'
    

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds:
        Ref: DelaySeconds
      MaximumMessageSize:
        Ref: MaximumMessageSize
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds:
        Ref: ReceiveMessageWaitTimeSeconds
      VisibilityTimeout:
        Ref: VisibilityTimeout
      KmsMasterKeyId: !FindInMap [NameRegion, !Ref 'AWS::Region', Idkms]

=============================
RUBY CODE HERE:
require 'cfn-nag/violation'
require_relative 'base'

class SqsQueueKmsMasterKeyIdRule < BaseRule
def rule_text
'SQS Queue should specify KmsMasterKeyId property'
end

def rule_type
Violation::FAILING_VIOLATION
end

def rule_id
'W48'
end

def audit_impl(cfn_model)
violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
sqs_queue.kmsMasterKeyId != 'arn:aws:kms:us-east-1:1234567890:key/1234567890' || sqs_queue.kmsMasterKeyId.nil?
end

violating_sqs_queues.map(&:logical_resource_id)
end
end

=========================================
whenever I execute Cloudformation templates using cfn-nag-custom, us-east-1 should accept/allow only above mentioned kms key . if I use/change any other KMS KEY in cloudformation template, cfn-nag-custom should through an error, states that incorrect KMS KEY where used in cloudformation template.

I am hoping, I have explained you in simple & easy way to understand the problem.

Please help me to achieve this logic. Thank you very very much in Advance!

**Comment by erickascic** [comment]
the issue is that the value in the model is "!FindInMap [NameRegion, !Ref 'AWS::Region', Idkms]", not the resolved value of arn:aws:kms:us-east-1:1234567890:key/1234567890

FindInMap isn't currently supported by the underlying parser for value substitution.  the best it can do is handle a !Ref to a Parameter with the key value.

To compare - change your template so that KmsMasterKeyId: arn:aws:kms:us-east-1:1234567890:key/1234567890.  The rule will behave more like what you expect then (with the inequality operator)

**Comment by ksredd** [comment]
Issue resolved now. Thank you very much for your timely help!
