### ISSUE TITLE
cfn-nag or(||) condition is not working as expected

### ISSUE THREAD

**Issue by ksredd** [stelligent/cfn_nag#427]
cfn-nag or(||) condition is not working as expected. Its working only with 1st value of condition. Let me explain you with steps:

HERE IS MY RUBY FILE:
require 'cfn-nag/violation'
require_relative 'base'

class SqsQueueKmsMasterKeyIdRule < BaseRule
def rule_text
'SQS Queue should specify KmsMasterKeyId property/value'
end

def rule_type
Violation::FAILING_VIOLATION
end

def rule_id
'W48'
end

def audit_impl(cfn_model)
violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
sqs_queue.kmsMasterKeyId != ( 'arn:aws:kms:us-east-1:7652890765440987650986400' || 'arn:aws:kms:us-east-2:7652890765440987650986400' || 'arn:aws:kms:ue-west-2:7652890765440987650986400')
end

violating_sqs_queues.map(&:logical_resource_id)
end
end

==========================
HERE IS MY CLOUDFORMATION TEMPLATE:
TEMPLATE-1:
AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Standard Queue
Parameters:
DelaySeconds:
MaximumMessageSize:
MessageRetentionPeriod:
ReceiveMessageWaitTimeSeconds:
UsedeadletterQueue:
VisibilityTimeout:

Resources:
SQSQueue:
Type: AWS::SQS::Queue
Properties:
DelaySeconds:
Ref: DelaySeconds
MaximumMessageSize:
Ref: MaximumMessageSize
MessageRetentionPeriod:
Ref: MessageRetentionPeriod
ReceiveMessageWaitTimeSeconds:
Ref: ReceiveMessageWaitTimeSeconds
VisibilityTimeout:
Ref: VisibilityTimeout
KmsMasterKeyId: 'arn:aws:kms:us-east-1:7652890765440987650986400' 

-------Result of this is, WORKING AS EXPECTED--------key here is i'm using KMS Key ID value as 1st or(||) condition value of ruby file
==============================================
TEMPLATE-2:
KmsMasterKeyId: 'arn:aws:kms:us-east-2:7652890765440987650986400' 
-----------Result of this is NOT WORKING AS EXPECTED---in correct behavior--key here is  i'm using KMS Key ID value as 2nd or(||) condition value of ruby file. I am changing only values in cloudformation template.

I hope, problem is clear to understand.

Please provide me the suggestion.

Thank you in Advance!

**Comment by erickascic** [comment]
the expression ( 'arn:aws:kms:us-east-1:7652890765440987650986400' || 'arn:aws:kms:us-east-2:7652890765440987650986400' || 'arn:aws:kms:ue-west-2:7652890765440987650986400') will evaluate as  'arn:aws:kms:us-east-1:7652890765440987650986400'.  you need to break out the comparison between the variable and your list of possible values

**Comment by ksredd** [comment]
Yes I have tried that as well, like below.

sqs_queue.kmsMasterKeyId !=  'arn:aws:kms:us-east-1:7652890765440987650986400' || sqs_queue.kmsMasterKeyId != 'arn:aws:kms:us-east-2:7652890765440987650986400' || sqs_queue.kmsMasterKeyId != 'arn:aws:kms:ue-west-2:7652890765440987650986400'


Its working only for 1st expression like (sqs_queue.kmsMasterKeyId !=  'arn:aws:kms:us-east-1:7652890765440987650986400'). If I use more then one expression(Or(||)) condition like above, its not working as expected.

Could you please suggest.

**Comment by erickascic** [comment]
the || operator is a "short-circuit" operator.  the first subexpression that is true makes the whole expression true and then it stops evaluating.

legal_arns = %w[arn1 arn2 arn3]
if !legal_arns.include?(sqs_queue.kmsMasterKeyId)
  # it's a violation
end

**Comment by ksredd** [comment]
Hey Thank you Erick!
Your inputs helped me in resolving my issue. I'm struggling from past few days, It really means a lot. 
I'm new to Ruby scripting, i'm basically an AWS  Developer.

Thanks for your kind help again. You made my day. :)
