### ISSUE TITLE
cfn nag should through error when tag[5]<=0

### ISSUE THREAD

**Issue by ksredd** [stelligent/cfn_nag#428]
Hello I have requirement,
 cfn-nag should through an error when cloudformation template have less then 5 Tags as mentioned below.

HERE IS CFN TEMPLATE:
---
AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Standard Queue
Parameters:{}
    Type: Number
    Default: '5'
Mappings:{}

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds:
        Ref: DelaySeconds
      MaximumMessageSize:
        Ref: MaximumMessageSize
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds:
        Ref: ReceiveMessageWaitTimeSeconds
      VisibilityTimeout:
        Ref: VisibilityTimeout
      KmsMasterKeyId: "arn:aws:kms:us-east-1:1234567890:key/1234567890"
      Tags:
       - Key: "name"
         Value: "abc1"
       - key: "name"
         Value: "abc2"
       - Key: "name"
         Value: "abc3"
       - Key: "name"
         Value: "abc4"
       - Key: "name"
         Value: "abc5"
--------------------------------------------------------------------
HERE IS RUBY FILE:
require 'cfn-nag/violation'
require_relative 'base'

class SqsQueueKmsMasterKeyIdRule < BaseRule
def rule_text
'SQS Queue should specify 5 Tags '
end

def rule_type
Violation::FAILING_VIOLATION
end

def rule_id
'W48'
end

def audit_impl(cfn_model)
violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
sqs_queue.Tags.nil?
end

violating_sqs_queues.map(&:logical_resource_id)
end
end

====================

Could you please suggest on this. It will be great help.

**Comment by erickascic** [comment]
depends on exactly what you are trying to do... must the tags match exactly?  are they a list of mandatory tags and then extras are ok?  do you care about the content of tag values? here's an example that just looks for mandatory tags:

`require 'cfn-nag/violation'
require 'cfn-nag/custom_rules/base'
require 'set'

class TagRule < BaseRule

  def rule_text
    'SQS Queue should specify 5 Tags '
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'W999'
  end

  def audit_impl(cfn_model)
    mandatory_tag_names = Set.new(%w[name1 name2 name3 name4 name5])
    violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
      tag_keys = sqs_queue.tags.map { |tag| tag['Key'] }
      !(mandatory_tag_names - Set.new(tag_keys)).empty?
    end

    violating_sqs_queues.map(&:logical_resource_id)
  end
end`

**Comment by ksredd** [comment]
Thank you for reply, Let me rewrite my problem statement,
I wanted to check only tag Key-name.

Cloudformation Template: cfn template can contain zero to 50 tag key-names but below mentioned 5 key-names are mandatory. if cloudformation template contain these 5 tag key-names(name1,name2,name3,name4,name5) then only cfn-nag should give success otherwise failure. 
==============================================

AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Standard Queue

Resources:
SQSQueue:
Type: AWS::SQS::Queue
Properties:
KmsMasterKeyId: "arn:aws:kms:us-east-1:1234567890:key/1234567890"
Tags:
- Key: "name1"
  Value: "abc1"
- key: "name2"
  Value: "abc2"
- Key: "name3"
  Value: "abc3"
- Key: "name4"
  Value: "abc4"
- Key: "name5"
  Value: "abc5"

============================================
I hope, now problem statement is clear.
Could you please let me know how can i achieve this with cfn-nag ruby file??

Thank you very much in Advance!

**Comment by ksredd** [comment]
highly appreciated your response

**Comment by erickascic** [comment]
i believe the code i posted before solves your reformulated problem statement.  in set terms, when you subtract the set of actual tag keys from the set of mandatory tag keys.... any left over tag keys in the result are mandatory tag keys that weren't in the set of actuals

**Comment by ksredd** [comment]
Hey Erick,
Thank you for reply.
I have executed cloudformation template with cfn-nag and below are the observations.
Case-1: When cloudformtion template have 5 mandatory tag keys, above code is working as expected # Success
Case-2: When cloudformtion template have 5 mandatory tag keys + some additional tag keys, above code is working as expected # Success
Case-3: When cloudformtion template have missed any mandatory tag keys, above code is working as expected # Success
CASE-4: WHEN CLOUDFORMATION TEMPLATE HAVE ZERO TAG KEYS(means there is NO Tag as property in cfn template), above CODE IS FAILING WITH BELOW ERROR. ideally it should fail and show error message, SQS should have 5 tag keys


Error description:
'Block in audit_impl': undefined method 'map' nil:NILClass ('NoMethodError')


Could you please suggest here.

**Comment by erickascic** [comment]
@ksredd give this a go.  if there are tags - check for the mandatory tags like we were doing.  if there are no tags then consider the resource to be in violation
```
require 'set'

class TagRule < BaseRule

  def rule_text
    'SQS Queue should specify 5 Tags '
  end

  def rule_type
    Violation::FAILING_VIOLATION
  end

  def rule_id
    'W999'
  end

  def audit_impl(cfn_model)
    mandatory_tag_names = Set.new(%w[name1 name2 name3 name4 name5])
    violating_sqs_queues = cfn_model.resources_by_type('AWS::SQS::Queue').select do |sqs_queue|
      if sqs_queue.tags
        tag_keys = sqs_queue.tags.map { |tag| tag['Key'] }
        !(mandatory_tag_names - Set.new(tag_keys)).empty?
      else
        true
      end
    end

    violating_sqs_queues.map(&:logical_resource_id)
  end
end
```
