### ISSUE TITLE
Docker image tags ahead of software version

### ISSUE THREAD

**Issue by kmoschkau** [stelligent/cfn_nag#433]
When pulling the `stelligent/cfn_nag:0.5.39` image from dockerhub and running `cfn_nag --version`, the software version is one minor release behind. Tag 0.5.39 has version 0.5.38 in it and tag 0.5.38  has version 0.5.37 software in it, etc. Seems like the versions got out of sync in tag 0.4.5

**Comment by erickascic** [comment]
@kmoschkau whoa thx for catching this.  the Dockerfile is blindly grabbing the latest from rubygems which is a mistake.

**Comment by erickascic** [comment]
Fixed in 0.5.43
