### ISSUE TITLE
S3 Bucket "BucketEncryption" KMSMasterKeyID validation

### ISSUE THREAD

**Issue by ksredd** [stelligent/cfn_nag#434]
I would like to validate KMSMasterKeyID for S3 bucket encryption(Detailed description: if KMS-key-id available in blow list then success else error ).

here is my kms-key list:
-----------------------------------------------------
arn_values=["arn:aws:kms:us-east-1:1234567890:key/1234567890","arn:aws:kms:us-east-2:1234567890:key/1234567890","arn:aws:kms:us-west-1:1234567890:key/1234567890"]
============================================
Here is my ruby file:
-------------------------
require 'cfn-nag/violation'
require_relative 'base'

class S3kmsidRule < BaseRule
def rule_text
'S3 bucket should specify valid KmsMasterKeyId value'
end

def rule_type
Violation::FAILING_VIOLATION
end

def rule_id
'W48'
end

def audit_impl(cfn_model)
arn_values=["arn:aws:kms:us-east-1:1234567890:key/1234567890","arn:aws:kms:us-east-2:1234567890:key/1234567890","arn:aws:kms:us-west-1:1234567890:key/1234567890"]

violating_buckets = cfn_model.resources_by_type('AWS::S3::Bucket').select do |bucket|
if bucket.BucketEncryption.nil?
true 
elsif ! bucket.BucketEncryption.nil?
!arn_values.include?(bucket.BucketEncryption.ServerSideEncryptionConfiguration.ServerSideEncryptionByDefault[kmsMasterKeyId])
end

violating_buckets.map(&:logical_resource_id)
end
end

SO HERE CFN-NAG RUBY FILE SHOULD CHECK ABOVE MENTIONED KMS-KEY ID AVAILABLE IN CLOUDFORMATION TEMPLATE OR NOT
========================================================
here is my cloudformation template:
-------------------------------------------
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with region specific encryption kms key-ID
Resources:
  EncryptedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-s3-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
	      KMSMasterKeyId: "arn:aws:kms:us-west-1:1234567890:key/1234567890"

COULD YOU PLEASE HELP ME HERE HOW TO ACCESS KMSMASTERKEY-ID AND HOW TO VALIDATE  valid KMS key-id?

I hope problem statement is clear.

**Comment by erickascic** [comment]
didn't test this code so caveat emptor, but would probably look something like this:
```
def noncompliant_bucket_encryption?(bucket_encryption)
  arn_values = %w[
    arn:aws:kms:us-east-1:1234567890:key/1234567890
    arn:aws:kms:us-east-2:1234567890:key/1234567890
    arn:aws:kms:us-west-1:1234567890:key/1234567890
  ]
  bucket.bucketEncryption['ServerSideEncryptionConfiguration'].select do |encryption_rule|
    !encryption_rule['ServerSideEncryptionByDefault']['KMSMasterKeyID'] || !arn_values.include?(encryption_rule['ServerSideEncryptionByDefault']['KMSMasterKeyID'])
  end
end

def audit_impl(cfn_model)
  violating_buckets = cfn_model.resources_by_type('AWS::S3::Bucket').select do |bucket|
    bucket.bucketEncryption.nil? || noncompliant_bucket_encryption?(bucket.bucketEncryption)
  end
  violating_buckets.map(&:logical_resource_id)
end
```

**Comment by ksredd** [comment]
Hey Erick, Thank you for reply.

I have implemented above logic but Not successful and below are observations.

Case:  irrespective of which KMS-Key ID  I use, cfn-nag is failing/incorrect response. Could you please have a look and help here.

**Comment by ksredd** [comment]
highly appreciate your response.

**Comment by erickascic** [comment]
what incorrect response are you seeing?

**Comment by ksredd** [comment]
cfn-nag is throwing error even if I use below mentioned KMS-Key ID in ruby file(this is for additional information, I have given one of the below value in cloudformation template so that value is same in ruby file & cloudformation template ) but ideally it should give success.

arn_values = %w[
    arn:aws:kms:us-east-1:1234567890:key/1234567890
    arn:aws:kms:us-east-2:1234567890:key/1234567890
    arn:aws:kms:us-west-1:1234567890:key/1234567890
  ]

**Comment by erickascic** [comment]
beware the case is incorrect in your test template.  it's KmsMasterKeyID instead of Id.

that said, one change to the conditions:
```
def noncompliant_bucket_encryption?(bucket_encryption)
  arn_values = %w[
    arn:aws:kms:us-east-1:1234567890:key/1234567890
    arn:aws:kms:us-east-2:1234567890:key/1234567890
    arn:aws:kms:us-west-1:1234567890:key/1234567890
  ]
  bucket_encryption['ServerSideEncryptionConfiguration'].select do |encryption_rule|
    !encryption_rule['ServerSideEncryptionByDefault']['KMSMasterKeyID'] || !arn_values.include?(encryption_rule['ServerSideEncryptionByDefault']['KMSMasterKeyID'])
  end
end

def audit_impl(cfn_model)
  violating_buckets = cfn_model.resources_by_type('AWS::S3::Bucket').select do |bucket|
    bucket.bucketEncryption.nil? || !noncompliant_bucket_encryption?(bucket.bucketEncryption).empty?
  end
  violating_buckets.map(&:logical_resource_id)
end
```
