### ISSUE TITLE
[Question] Contributing custom rules

### ISSUE THREAD

**Issue by dscpinheiro** [stelligent/cfn_nag#435]
Hi!

I work at AWS and we've been using cfn_nag in our CI/CD pipelines.
We've noticed more common patterns and we think it would be beneficial to add a few custom rules to cfn_nag so that we can catch these problems earlier in the development process of CloudFormation templates.

Here are the patterns we identified so far:
1. DynamoDB table should explicitly indicate billing mode (provisioned or pay per request) = WARNING
    We understand this rule doesn’t really fit in the "insecure infrastructure" category, but we've seen cases where leaving the default eventually caused throttling issues later (as the tables did not have auto scaling configured). Does this rule fall in the scope of cfn-nag as a good common rule for use?
2. DynamoDB table should enable server-side encryption using a CMK stored in KMS = WARNING
    Even though the default settings already encrypt the data at rest, the key is owned by DynamoDB.
3. RDS instance should have backup retention period greater than 0 = WARNING
4. RDS instance should have deletion protection enabled = FAILING

My questions are:
- Would these patterns be a good addition to cfn_nag?
- If so, we would like to contribute by sending PRs for these proposed additions. Do you suggest to create one PR with all of the rules (above)? Or is it better to split them into separate PRs?

Thanks in advance!

**Comment by erickascic** [comment]
@dscpinheiro thx for using cfn_nag!  i think these are excellent rules to add to the universal set and we'd welcome your PRs.  ideally if you could issue a PR per rule, that makes reviewing easier.

unless you already have some code ready - i can take a stab at bullet number 2.  there may be a rule that just needs to be subclassed.  iirc we've done the "missing KMS key" rule before for a few resources and if there isn't already some common code for it, it probably deserves that common code.

**Comment by dscpinheiro** [comment]
That's great to hear!

We already have some code, I'll create the PRs this afternoon (we can change the bullet number 2 if you think there's a better way to do it).

**Comment by dscpinheiro** [comment]
I've created the PRs: 
- #436
- #437 
- #438
- #439

For the rule_id, I ran _cfn_nag_rules_ locally and picked the next available numbers. If they conflict with something already in development, please let me know and I'll fix them.
