### ISSUE TITLE
DeletionProtection is not Applicable for RDS Instances

### ISSUE THREAD

**Issue by katalmayi** [stelligent/cfn_nag#445]
Hi! 
cfn_nag enforces DeletionProtection for all RDS Instances, but per Amazon's docs, this boolean flag is NOT applicable for Aurora RDS instances, only for the cluster:

> DeletionProtection
A value that indicates whether the DB instance has deletion protection enabled. The database can't be deleted when deletion protection is enabled. By default, deletion protection is disabled. For more information, see Deleting a DB Instance.
Amazon Aurora
Not applicable. You can enable or disable deletion protection for the DB cluster. For more information, see CreateDBCluster. DB instances in a DB cluster can be deleted even when deletion protection is enabled for the DB cluster.

[Amazon docs with the above cited block](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html)

When we attempt to set the parameter against the DB instances CFN blows up with this error:

> _The specified DB Instance is a member of a cluster. Modify deletion protection for the DB Cluster using the ModifyDbCluster API (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination;_

If we try to follow the recommendation of the AWS docs, cfn_nag complains:

49 | cfn_nag CloudFormation/RDS.template
50 | ------------------------------------------------------------
51 | CloudFormation/RDS.template
52 | ------------------------------------------------------------------------------------------------------------------------
53 | ·[31m\| FAIL F80·[0m
54 | ·[31m\|·[0m
55 | ·[31m\| Resources: ["DBInstance", "SecondaryDBInstance"]·[0m
56 | ·[31m\| Line Numbers: [239, 303]·[0m
57 | ·[31m\|·[0m
58 | ·[31m\| RDS instance should have deletion protection enabled·[0m

**Comment by erickascic** [comment]
@katalmayi please give 0.5.54 a try.  thx!

**Comment by katalmayi** [comment]
@erickascic no dice yet, still getting the same validation fail on the RDS template for aurora db instances.

**Comment by erickascic** [comment]
@katalmayi thx for your patience.  the reason the rule isn't working for you is that FindInMap isn't substituted for the ultimate value so the rule can't tell whether it's aurora or not.  I'm working through a prototype to enhance the underlying parser to substitute the values:

https://github.com/stelligent/cfn-model/issues/78

**Comment by erickascic** [comment]
0.5.55 includes FindInMap support in tandem with properly ignoring aurora

**Comment by katalmayi** [comment]
great success (it worked 👍 ). Thank you! (bow)
