### ISSUE TITLE
CFN Nag not replacing references using the parameter JSON file

### ISSUE THREAD

**Issue by SumoSourabh** [stelligent/cfn_nag#455]
Hi Team,

I am trying to use the CFN NAG to check for pre deploy condition by passing template along with some parameters values.

Let us consider, I have a resource (IAM Role) as below 
  HelperRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: awstestingLambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - tag:TagResources
                  - tag:UntagResources
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:AddTags
                  - elasticloadbalancing:RemoveTags
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                **Resource: !Ref Resource**

Here Resource is taken from a parameter, I am passing parameter json as

[
  {
    "ParameterKey": "Resource",
    "ParameterValue": "*"
  }
]

or 

{
  "Parameters": {
    "Resource": "*"
  }
}

command used are 

cfn_nag template -m json OR cfn_nag template --parameter-values-path=json
cfn_nag_scan -i template -a json OR cfn_nag_scan -i template --parameter-values-path=json

As per readme, it should replace the parameter values and then check for rule.

Can you please point me in how to use the parameter json to resolve the parameters in CF?

**Comment by erickascic** [comment]
@SumoSourabh you are doing everything correctly.  unfortunately the underlying model doesn't support parameter substitutions "under" the top level of properties.  for example, if you set Policies to !Ref Resource - it would resolve the way you expect.  "underneath" the top level of properties, the model treats those as a hash/dictionary instead of a first class model element.

i have some cycles today to consider solving this problem but in the meantime i'm afraid it won't behave as (we'd all!) want.

**Comment by SumoSourabh** [comment]
Thanks for the quick reply.

My Use case here is :- 

I am trying to validate some parameter for custom resources (other than empty and common checks which I am doing thanks to the Custom Rules) before deployment.

Let me know if you are able to get through it and have the intrinsic function references resolved.

**Comment by erickascic** [comment]
@SumoSourabh give 0.5.60 a try.

**Comment by SumoSourabh** [comment]
@erickascic Thanks for the new version.

I checked it worked for the !Ref.

Did anything needs to be done to get it working for !Sub function. It was not replacing values for Sub function. 

For eg:
!If [install_cloud_watch_metric_source, !Sub "_sourceCategory=${CloudWatchMetricsSourceCategoryName}", "_sourceCategory=myconstantvalue"]

This condition was replaced with !Sub "_sourceCategory=${CloudWatchMetricsSourceCategoryName}".

Sorry for the trouble.

**Comment by erickascic** [comment]
@SumoSourabh the Sub function isn't yet supported by cfn-nag.  it's actually in the cfn-model backlog already... i can prioritize this since you are asking for it

**Comment by erickascic** [comment]
@SumoSourabh i think i have something close to release for Sub, but going to close this issue an open a fresh one to capture the work.  thx!
