### ISSUE TITLE
Support partial evaluation of other Cfn Functions

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#457]
Do a best effort on evaluating: Sub, GetAZs, Select, Join, Split, Base64

Anything external or that requires computation from the cfn service is left alone as always.  Therefore GetAtt, Cidr, ImportValue, Transform still passed through as-is.  This includes embedded references within Subs

This is in response to feature request from @SumoSourabh

**Comment by SumoSourabh** [comment]
Thanks @erickascic . It helps a lot.

**Comment by erickascic** [comment]
released in 0.5.61

**Comment by SumoSourabh** [comment]
Thanks @erickascic . I will try it out.
