### ISSUE TITLE
SecretsManagerSecretKmsKeyIdRule fails instead of Warns

### ISSUE THREAD

**Issue by gitmlynch** [stelligent/cfn_nag#460]
According to the titles for #443 and #444 `SecretsManagerSecretKmsKeyIdRule` should warn rather than fail. So, shouldn't [this line](https://github.com/erickascic/cfn_nag/blob/master/lib/cfn-nag/custom_rules/SecretsManagerSecretKmsKeyIdRule.rb#L12) be `Violation::WARNING` instead of `Violation::FAILING_VIOLATION`?

We have a pipeline that is failing due to the `SecretsManagerSecretKmsKeyIdRule`. Output:

```
+ cfn_nag_scan --input-path cloudFormation/templates
------------------------------------------------------------
cloudFormation/templates/projectsTopic.yaml
------------------------------------------------------------------------------------------------------------------------
[33m| WARN W47[0m
[33m|[0m
[33m| Resources: ["****"][0m
[33m| Line Numbers: [11][0m
[33m|[0m
[33m| SNS Topic should specify KmsMasterKeyId property[0m

Failures count: 0
Warnings count: 1
------------------------------------------------------------
cloudFormation/templates/documentdb.yaml
------------------------------------------------------------------------------------------------------------------------
[31m| FAIL F81[0m
[31m|[0m
[31m| Resources: ["****"][0m
[31m| Line Numbers: [71][0m
[31m|[0m
[31m| Secrets Manager Secret should explicitly specify KmsKeyId[0m

Failures count: 1
Warnings count: 0
```

**Comment by erickascic** [comment]
@gitmlynch so.... the reasoning behind making that a fail is that witout a KmsKeyId a secret cannot be shared cross-account vs. those other resources which don't work that way.  i can bump this over to a warning though if you feel strongly.  i guess warning probably is better.... but maybe i should fill out the description for the why a little better

**Comment by gitmlynch** [comment]
> @gitmlynch so.... the reasoning behind making that a fail is that witout a KmsKeyId a secret cannot be shared cross-account vs. those other resources which don't work that way. i can bump this over to a warning though if you feel strongly. i guess warning probably is better.... but maybe i should fill out the description for the why a little better

Thank you for the speedy reply.

I do think that a warning is more appropriate. Making it a failure builds in an assumption that passwords _should_ be shared across accounts. I disagree with that. In general, I think it is a better security practice to avoid sharing secrets across accounts. I do agree that elaborating on the reason for the rule would be beneficial too.

**Comment by erickascic** [comment]
well - the sharing across accounts is important as accounts start multiplying and you have legitimate secrets to share.  don't want to replicate those across accounts but.... that said i agree on the warning and it's in 0.6.0 that was just released.  

thx for using cfn_nag and having the patience to work through this with me!

**Comment by gitmlynch** [comment]
> thx for using cfn_nag and having the patience to work through this with me!

Thank you so very much for your responsiveness. We are thrilled to have the benefits of cfn_nag.

**Comment by gitmlynch** [comment]
Hey @erickascic, a quick word from the field... today, cfn_nag caught that one of our developers was trying to do something undesirable from a security pov. As a result we were able to point them in the right direction. So thanks again for all your work. ⭐
