### ISSUE TITLE
No Option to ignore no resource failure 

### ISSUE THREAD

**Issue by JBarnes94** [stelligent/cfn_nag#468]
I am looking at running cfn_nag as a pre-commit hook. 
The easiest way i can see this is running against all json, yaml and template files. 
I am running into an issue that this will run it against non cloudformation file and fail due to a lack of resources 

| FAIL FATAL
|
| Illegal cfn - no Resources

Is there a way to Ignore files that that contain no resources

**Comment by erickascic** [comment]
@JBarnes94 you can control the pattern for what files will be analyzed with the --template_pattern argument.  the default pattern is '..*\.json|..*\.yaml|..*\.yml|..*\.template'.  this likely doesn't help you though if you are pointing cfn_nag at a directory filled with a diverse set of files.  one possibility is to set the pattern to *.template.json and enforce a naming standard on your cfn templates....

that said, i can add a command line argument to force ignoring malformed templates

**Comment by erickascic** [comment]
@JBarnes94 0.6.5 is released with an --ignore-fatal argument.  default is false, so you'll have to set it in order to do the necessary.
