### ISSUE TITLE
Not able to include custom rules in a whitelist profile

### ISSUE THREAD

**Issue by steenblik** [stelligent/cfn_nag#488]
I have a custom rule which I've just developed. This rule works well but I've noticed that if I add this rule to a profile and then pass the profile with --profile-path the rule is not run. If I omit --profile-path the rule is run.

I'm running cfn_nag 0.6.7

**Comment by arothian** [comment]
@accuracy27 Thanks for reporting this issue. I wasn't able to directly reproduce this. Can you provide some more details on the commands and profile you are using?
