### ISSUE TITLE
Add rule to look for plaintext "master" username and password for RDS::DBInstance

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#49]
In DBInstance, make sure of a few things:

1. MasterUsername and MasterUserPassword should not be specified inline with values
2. Given MasterUsername and MasterUserPassword are Refs to parameters - they should not have defaults
3. Given MasterUsername and MasterUserPassword are Refs to parameters - make sure the parameters are NoEcho

**Comment by erickascic** [comment]
0.3.23 includes password not username

**Comment by byronic** [comment]
Update: I believe this was already completed. Passing to @erickascic to verify
