### ISSUE TITLE
undefined method `request' for nil:NilClass

### ISSUE THREAD

**Issue by txynidakis** [stelligent/cfn_nag#509]
Hi

I've tried to update/re-install cfg-nag using
* gem install cfg-nag
* brew gem install cfn-nag

I get the error 
 $ gem update cfn-nag
Updating installed gems
Updating cfn-nag
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass

my ruby skills are non-existant

$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
$ gem -v
3.2.4

Any help will be much appreciated!!

**Comment by pethers** [comment]
Think https://github.com/stelligent/cfn-model/pull/86 need to merged to support ruby 3

**Comment by rjcoelho** [comment]
Same issue here. 
What can we do ?
