### ISSUE TITLE
Homebrew gem error

### ISSUE THREAD

**Issue by dscpinheiro** [stelligent/cfn_nag#544]
I'm trying to update cfn_nag to the latest version on my laptop, but the `brew gem upgrade cfn-nag` command is returning the following error:
```
Error: gem-cfn-nag: Calling `def fetch` in a subclass of `Formulary::FormulaNamespace75119bedc98402d31291edc5f9cbfd84::RubyGemsDownloadStrategy` is disabled! Use `def fetch(timeout: nil, **options)` and output a warning when `options` contains new unhandled options instead.
```

The same message is returned when running `brew gem uninstall cfn-nag`.

Here are some more details:
```
~ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

~ system_profiler SPSoftwareDataType
Software:
    System Software Overview:
        System Version: macOS 10.15.7 (19H524)
        Kernel Version: Darwin 19.6.0
```

**Comment by will-gant** [comment]
Hi there. I'm hitting the same issue.

**Comment by arothian** [comment]
Thanks for reporting; I believe this is an issue with brew-gem. Can you try updating to v1.1.1 `brew upgrade brew-gem`

https://github.com/sportngin/brew-gem/pull/69

**Comment by aassadza** [comment]
> Thanks for reporting; I believe this is an issue with brew-gem. Can you try updating to v1.1.1 `brew upgrade brew-gem`
> 
> [sportngin/brew-gem#69](https://github.com/sportngin/brew-gem/pull/69)

Thanks. That `brew upgrade brew-gem` fixed it for me

**Comment by dscpinheiro** [comment]
That worked for me too, thanks!
