### ISSUE TITLE
pass parameter file to cfn nag

### ISSUE THREAD

**Issue by sriram9707** [stelligent/cfn_nag#549]
how to pass parameter files for cloudformation templates in cfn-nag scan?

**Comment by arothian** [comment]
Hi @sriram9707 , take a look at this section https://github.com/stelligent/cfn_nag#setting-template-parameter-values

Parameter values can be specified in json. You then pass the file via `--parameter-values-path=<filepath>`

**Comment by sriram9707** [comment]
hey @arothian  thanks for that. im using cfn_nag in code build to scan our cfn templates. is there a way to fail builds if there are more number of warning/builds using cli flags ?

**Comment by arothian** [comment]
There isn't any functionality right now for failing if the number of warnings/failures increases between executions.
