### ISSUE TITLE
Add `--exit-zero` parameter to get cfn_nag to exit with zero status

### ISSUE THREAD

**Issue by twitu** [stelligent/cfn_nag#550]
This is useful in build pipelines where warnings need to be ignored and the build needs to proceed. This is a bit related #292 but I'm specifically asking for a parameter to exit with zero when configured.

Current workaround is to "catch" the return value.

`export IGNORE_RESULT=$(cfn_nag_scan -i cdk.out/ -t ..*\.template\.json$ -o json > report/cfn-nag-report.json)`

**Comment by arothian** [comment]
Thanks for the feedback @twitu . You should be able to ignore warnings by passing `--fail-on-warnings` or configuring a global exclusion list via `----blacklist-path` for the rules you don't wish to use.

Let me know if those options don't work

**Comment by tbenbrahim** [comment]
`|| true` does that generically

`cfn_nag_scan --input-path aws/*.yaml > cloudformation-scan.txt || true`
