### ISSUE TITLE
Directory not scanned recursively when running in Docker

### ISSUE THREAD

**Issue by paulsiersma** [stelligent/cfn_nag#554]
When I try to run the command in the docs for running cfn_nag using the docker image and mapping my local cfn templates to a docker location:

`docker run -v `pwd`/infra:/templates -t stelligent/cfn_nag /templates`

I expect to be able to provide the directory for it to recursively scan all files in the directory. 

Instead I get `Is a directory @ io_fillbuf (Errno::EISDIR)` error message. Am I doing something wrong here?

I'm running this on ubuntu-latest image (in a Azure DevOps pipeline task). If I specify on of the templates in the dir by providing a full file path, it works.

**Comment by arothian** [comment]
Hi @paulsiersma , 

This is poorly documented, but this project actually provides two executables, `cfn_nag` and `cfn_nag_scan`. Only `cfn_nag_scan` supports scanning all files in a directory, and the docker image by default uses `cfn_nag`.

You should be able to get this to work by overriding the entrypoint. Something like
```docker run --entrypoint cfn_nag_scan -v $(pwd)/infra:/templates -t stelligent/cfn_nag --input-path /templates```

`cfn_nag_scan --help` to see the full options available.

**Comment by paulsiersma** [comment]
That's great, thanks a lot for explaining. I see now it says `cfn_nag_scan` and not `cfn_nag` where it mentions the directory scanning in the docs, I failed to notice the difference. Thanks again.
