### ISSUE TITLE
ignore-fatal is ignoring normal errors as well

### ISSUE THREAD

**Issue by BalmanRawat** [stelligent/cfn_nag#555]
**Summary**
I wanted to ignore non-cloudformation/fatal CloudFormation templates using `--ignore-fatal` but it is ignoring normal errors as well. Am I missing something here or this is the expected behavior. Please find the screenshots below for further context

**Screenshots**
- `cfn_nag_scan --input-path service.yaml`
<img width="1329" alt="Screen Shot 2021-06-03 at 16 11 13" src="https://user-images.githubusercontent.com/8892649/120630207-53788080-c486-11eb-815a-239722544d00.png">

- `cfn_nag_scan --input-path service.yaml --ignore-fatal`
<img width="1324" alt="Screen Shot 2021-06-03 at 16 12 14" src="https://user-images.githubusercontent.com/8892649/120630338-773bc680-c486-11eb-936c-289b5302cb59.png">

**Comment by arothian** [comment]
Hi @BalmanRawat , thanks for the report. I agree, it looks like this is removing normal failure results as well. I'll see if we can fix this up.

**Comment by arothian** [comment]
@BalmanRawat , if you are able, can you try using the proposed fix in https://github.com/stelligent/cfn_nag/pull/556 and verify that this resolves your issue?

**Comment by BalmanRawat** [comment]
Thank you @arothian that works.
