### ISSUE TITLE
SARIF Format Support on Output for cfn_nag

### ISSUE THREAD

**Issue by NickLiffen** [stelligent/cfn_nag#568]
Hey 👋 

I didn't know where else to post this so thought I would open an issue. If this is better moved to a GitHub discussion let me know. 

I'm Nick from GitHub, specifically on the GitHub Advanced Security (GHAS) product. I am a big user of `cfn_nag`, and I think it's great to help people track possible security patterns within their cloud formation templates. 

One thing I would **love** is for this tool to support a [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) output. SARIF is an industry standard for static analysis. 

We have seen many other linting tools support SARIF such as [eslint](https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif), as well as other security tools: [CodeQL](https://codeql.github.com/docs/), etc. 

So, why am I asking for SARIF support? Right now, GitHub Code Scanning (as part of GitHub Advanced Security) supports any file which is in the format of SARIF. That means any data can be uploaded to Code Scanning. We are seeing more and more teams starting to track security and quality alerts within Code Scanning, and I think it would be great if `cfn_nag` results could be uploaded to Code Scanning. 

All I see this being is the following:

```
cfn_nag_scan --input-path template.yml --output-format sarif
```

Right now it supports JSON, etc. If it could also support SARIF, that would be amazing :) 

Love to hear your thoughts 👍  Also happy to discuss this any further 👍 I think this would be a great feature 👍

**Comment by NickLiffen** [comment]
We could then add it as an option on the GitHub Action, which would automatically upload the results to Code Scanning, which I think would be a really nice experience 👍

**Comment by NickLiffen** [comment]
Amazing 💯 Thanks @arothian. I would contribute towards this work but as a developer myself, I must admit Ruby is not my strong suit 😢 

Some tools that may be useful to you:

- [SARIF Validator](https://sarifweb.azurewebsites.net/Validation)
- [SARIF Tutorials](https://github.com/microsoft/sarif-tutorials)

If you would like to validate anything please feel free to let me know 👍

**Comment by arothian** [comment]
> @arothian thanks for this! Is there any way I could run cfn_nag off this branch by any chance? I can just quickly test this by getting the SARIF and uploading it to the GitHub Code Scanning portal.

@NickLiffen You should be able to. If you have the branch locally and ruby 2.5+, `bundle install` will install any dependencies. Then you can run `bundle exec cfn_nag_scan -o sarif --input-path ...` to run a scan using the branch's changes.

**Comment by arothian** [comment]
@NickLiffen Once #581 is merged I think you should be able to follow the example in that PR and get this working.

**Comment by arothian** [comment]
Closing as we published a new action that handles the SARIF format and upload for use with Code Scanning (https://github.com/marketplace/actions/cfn-nag-sarif-upload)
