### ISSUE TITLE
Look for wildcards in AWS::IoT::Policy

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#57]

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842090

**Comment by twellspring** [comment]
AWS::IoT::Policy follow the same format as a IAM policy document per https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html so will have similar rules (wildcard on resource, wildcard on action.

```
$ cfn_nag_rules   | grep -i "IAM policy"
W12 IAM policy should not allow * resource
W16 IAM policy should not allow Allow+NotAction
W22 IAM policy should not allow Allow+NotResource
F4 IAM policy should not allow * action
```

**Comment by Mr-Lizard** [comment]
would the cfn_model have to be updated to support AWS:IoT::Policy ?  I'm currently getting an 

>  undefined method `wildcard_allowed_actions' for nil:NilClass (NoMethodError)

 while trying to use code modified from AWS::IAM::Policy.
