### ISSUE TITLE
Check for inbound permissions on AWS::GameLift::Fleet

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#58]
This could be more of a spike - I don't know anything about GameLift but.... looks like you can specify port ranges.... and wide ranges are likely a smell

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842089

**Comment by pshelby** [comment]
From my research it seems like most [use cases will not need port ranges (page 106)](https://docs.aws.amazon.com/gamelift/latest/developerguide/gamelift-dg.pdf), so it should be safe to at least warn on any range.  I'll create a PR for the port range rule shortly.

I also considered warning on wide subnet masks, however if the game needs to be open to the internet that could be a legitimate value.

**Comment by Mr-Lizard** [comment]
Warning on something just because it is a range would seem 'alarmist' -
there should be actual reason why something
is being warned, not that it is a construct that isn't popular.

**Comment by pshelby** [comment]
> Warning on something just because it is a range would seem 'alarmist' - there should be actual reason why something is being warned, not that it is a construct that isn't popular.

@Mr-Lizard I understand where you're coming from, and I certainly don't want to spam users unnecessarily.  However in this case I would consider it more informative than alarmist.  I'm absolutely open to more conversation about this, and I'll wait to submit a PR until we discuss further.

Here are some of my considerations:
- Following the AWS principal of least privilege, it's always safer to lock down access to resources as much as possible--especially when opening ingress ports to EC2 instances.  If someone was testing by opening ports 1-65536 and forgot to change it, this will serve as a reminder.
- As this is only a warning, it will not force a non-zero return code.  If any pipelines are using this and run across this rule, they won't fail but will have the output available for review (see examples below).
- If the user truly does need a range, they can disable this warning globally or even for the particular Fleet in question (see examples below).

Example warning thrown by the rule:
```
$ cat spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  InsecureGameLiftFleet:
    Type: AWS::GameLift::Fleet
    Properties:
      EC2InboundPermissions:
        - FromPort: 1
          IpRange: 10.1.0.0/24
          Protocol: TCP
          ToPort: 60000
        - FromPort: 10666
          IpRange: 0.0.0.0/0
          Protocol: TCP
          ToPort: 10666
      EC2InstanceType: t2.micro
      Name: InsecureGameLiftFleet
```
```
$ bundle exec cfn_nag --rule-directory lib spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
------------------------------------------------------------
spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
------------------------------------------------------------------------------------------------------------------------
| WARN W57
|
| Resources: ["InsecureGameLiftFleet"]
| Line Numbers: [6]
|
| GameLift fleet EC2InboundPermissions found with port range instead of just a single port

Failures count: 0
Warnings count: 1
```
```
$ echo $?
0
```

Example suppressing the rule for a specific resource:
```
$ cat spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  InsecureGameLiftFleet:
    Type: AWS::GameLift::Fleet
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W57
            reason: "This game needs a range of ports open to accept incoming connections."
    Properties:
      EC2InboundPermissions:
        - FromPort: 1
          IpRange: 10.1.0.0/24
          Protocol: TCP
          ToPort: 60000
        - FromPort: 10666
          IpRange: 0.0.0.0/0
          Protocol: TCP
          ToPort: 10666
      EC2InstanceType: t2.micro
      Name: InsecureGameLiftFleet
```
```
$ bundle exec cfn_nag --rule-directory lib spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
------------------------------------------------------------
spec/test_templates/yaml/gamelift/fleet_open_to_port_range.yml
------------------------------------------------------------
Failures count: 0
Warnings count: 0
```
```
$ echo $?
0
```
