### ISSUE TITLE
Add rules for AWS::ElasticLoadBalancingV2::Listener ssl policy

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#60]
We could be opinionated about this and force TLS 1.1 and 1.2, or.... we could define check per policy and let the user add the particular rules to a profile

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842087

**Comment by thegonch** [comment]
PR created at: https://github.com/stelligent/cfn_nag/pull/354
