### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by akkadaya** [stelligent/cfn_nag#619]
I can't install it on the new Debian Bookworm. I wanted to raise an issue here but I noticed this project hasn't got any updates since June 2022!
Is it dead? are there other good alternatives?

Thanks

**Comment by ericzbeard** [comment]
I can't get cfn-nag to install on Mac OS any more, looks like the brew formula is gone. cfn-guard is an option.

**Comment by deanhtid** [comment]
yeah seems like its no longer maintained 😩 just tried to run an update and failed. I'll take a look at cfn-guard

**Comment by mcgradyjp** [comment]
Do you get any actual errors? I tried the install on Debian Bookworm and found no issues.

**Comment by nathandebalthasar** [comment]
I guess you can use [cdk-nag](https://github.com/cdklabs/cdk-nag) which is inspired by this project @akkadaya

**Comment by mcgradyjp** [comment]
closing issue due to no response with actual error reports and no errors on install.
