### ISSUE TITLE
Warn on VPC without a AWS::EC2::FlowLog attached to it

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#63]
Could be defined in another template so just warn

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842086

**Comment by twellspring** [comment]
Warn if resources_by_type(AWS::EC2::VPC) exists and no resources_by_type(AWS::EC2::FlowLog) exist

Checking more specifically that the VPC is specified in the FlowLog ResourceID is possible but would mean this rule would warn if someone decided to use flow logs on subnets rather than the full vpc.

**Comment by archetypalsxe** [comment]
Not able to assign myself, but I am working on this feature
