### ISSUE TITLE
Look for AdministratorAccess managed policy in IAM Role

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#75]
If IAM::Role has ManagedPolicyArns that include AdministratorAccess, or any other uber powerful AWS managed policies...this should at least be a warning

**Comment by melusom** [comment]
I'd also add `PowerUserAccess` and `IAMFullAccess` to that list. Rule suppression will allow users to ignore this warning for certain resources, but I think we can generally agree that this is not the recommended config and should be called out.

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842072
