### ISSUE TITLE
FAIL FATAL  Resources/AppELB/Properties/AppCookieStickinessPolicy] not a sequence

### ISSUE THREAD

**Issue by MaanasaDornala** [stelligent/cfn_nag#81]
FAIL FATAL
|
| Basic CloudFormation syntax error:[#<Kwalify::ValidationError: [/Resources/AppELB/Properties/AppCookieStickinessPolicy] not a sequence.>, #<Kwalify::ValidationError: [/Resources/AppELB/Properties/Listeners/0/PolicyNames] not a sequence.>]

Failures count: 1
Warnings count: 0

Not sure whats going wrong:-

Here is the snippet:-

"AppELB": {
            "Type": "AWS::ElasticLoadBalancing::LoadBalancer",
            "Properties": {
				    "LoadBalancerName": {"Fn::Join" : [ "-", [ {"Ref": "appName"}, {"Ref": "nSdlcEnv"},{"Ref": "envNum"}, {"Ref": "Service"} ] ] },
		        "Scheme": "internal",
                "CrossZone": "true",
                "SecurityGroups": { "Ref": "AppELBSecurityGroup" },
                "AppCookieStickinessPolicy": {
                   "Fn::If": [
                     "EnableAppCookie",
                     [ { "PolicyName": "AppStickiness", "CookieName": { "Ref" : "ELBAppCookieName" } } ],
                     {"Ref" : "AWS::NoValue"}
                   ]
                },
                "Subnets": { "Ref": "AppELBSubnets" },
                "Listeners": [
                    {
                        "LoadBalancerPort": { "Ref": "AppELBListenerPort" },
                        "PolicyNames": {
                          "Fn::If": [
                             "EnableAppCookie",
                             [ "AppStickiness" ],
                             {"Ref" : "AWS::NoValue"}
                          ]
                        },
                        "InstancePort": { "Ref": "AppELBInstancePort" },
                        "Protocol": { "Ref": "AppELBListenerProtocol" },
                        "SSLCertificateId": {
                          "Fn::If": [
                            "EnableSSlCert",
                            { "Ref" : "SSLCertificateARN" },
                            {"Ref" : "AWS::NoValue"}
                          ]
                        }
                    }
                ],
                "HealthCheck": {
                    "Target": {
                      "Fn::If": [
                        "HTTPHealthCheck",
                        {
                          "Fn::Join": [ "", [
                            { "Ref": "AppHealthCheckProtocol" },
                            ":",
                            { "Ref": "AppHealthCheckPort" },
                            { "Ref": "AppHealthCheckPath" }
                          ] ]
                        },
                        {
                          "Fn::Join": [ "", [
                            { "Ref": "AppHealthCheckProtocol" },
                            ":",
                            { "Ref": "AppHealthCheckPort" }
                          ] ]
                        }
                      ]
                    },
                    "HealthyThreshold": "2",
                    "UnhealthyThreshold": { "Ref": "AppELBUnhealthyThreshold" },
                    "Interval": { "Ref": "AppELBIntervalThreshold" },
                    "Timeout": { "Ref": "AppELBTimeoutThreshold" }
                },

                "Tags": [
                    { "Key": "Name", "Value": {"Fn::Join" : [ "-", [ {"Ref": "nOrg"}, {"Ref": "nGroup"}, {"Ref": "nSdlcEnv"}, {"Ref": "appName"}, {"Ref": "Service"}, "lb" ] ] } },
                    {
                      "Key": "cName",
                      "Value": {
                        "Ref": "PublicHostName"
                      }
                    }
                ]
            }
        }

**Comment by erickascic** [comment]
The parser is being too strict on the "PolicyNames" field.  It believes this should be a sequence of values - but while this is normally true, it's legal to have the "Fn::If" object as a value instead.  Will have a fix out shortly

**Comment by MaanasaDornala** [comment]
@erickascic Thank you

**Comment by erickascic** [comment]
@MaanasaDornala give 0.3.9 a go
