### ISSUE TITLE
Add a fail-on-warnings command line option

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#84]

**Comment by melusom** [comment]
Is the current behavior to only fail on `FAIL`s? In my experience any warning or failure returns a non-zero exit code. However, I think that the exit codes should differ when output is clean (right now zero), contains only warnings (some nonzero value), or contains at least one failure (some other nonzero value).

**Comment by jbaum-cmcrc** [comment]
Certainly it's the documented behaviour that "A warning will return a zero/success exit code." (per `README.md`). If the actual behaviour is to fail on warning, the documentation should be updated...

**Comment by byronic** [comment]
Current behavior is `FAIL`s result in a nonzero exit code, `WARN`s result in a zero/success exit code.

```
$ bin/cfn_nag spec/test_templates/json/neptune/with_encryption_false_boolean.json 
{
  "failure_count": 1,
  "violations": [
    {
      "id": "F30",
      "type": "FAIL",
      "message": "Neptune database cluster storage should have encryption enabled",
      "logical_resource_ids": [
        "NeptuneDBCluster"
      ]
    }
  ]
}
$ echo $?
1
$ bin/cfn_nag spec/test_templates/json/iam_role/iam_role_not_action.json 
{
  "failure_count": 0,
  "violations": [
    {
      "id": "W15",
      "type": "WARN",
      "message": "IAM role should not allow Allow+NotAction",
      "logical_resource_ids": [
        "NotActionRole"
      ]
    },
    {
      "id": "W11",
      "type": "WARN",
      "message": "IAM role should not allow * resource on its permissions policy",
      "logical_resource_ids": [
        "NotActionRole"
      ]
    }
  ]
}
$ echo $?
0
``` 

I'll work on adding the parameter.
