### ISSUE TITLE
Add ability to install through homebrew

### ISSUE THREAD

**Issue by erickascic** [stelligent/cfn_nag#86]

**Comment by erickascic** [comment]
https://www.pivotaltracker.com/story/show/164842066

**Comment by Mr-Lizard** [comment]
I'd like to take a stab at this, if you would assign me.

**Comment by jesseadams** [comment]
@Mr-Lizard It wont let me assign it to you as you aren't a member of our org. However, feel free to knock it out! We'll check in with you before you start work on it if it comes to that.

**Comment by erickascic** [comment]
Not sure if it would make life easier or dovetail but... the ruby-packer tool is something I'll mention here:

brew install squashfs
curl -L http://enclose.io/rubyc/rubyc-darwin-x64.gz | gunzip > rubyc
./rubyc --gem=cfn-nag --gem-version 0.3.89 cfn_nag

**Comment by Mr-Lizard** [comment]
I have the beginnings of a workable formula.  However, it would probably be best to create a 'Homebrew_taps' repository to use as a 'tap' per standard homebrew conventions. Also, what email should I use for the point of contact in the formula ?

**Comment by jesseadams** [comment]
@Mr-Lizard Thanks for working on this. You can use "Stelligent cfn-nag Team <cfn-nag@stelligent.com>" for a point of contact.

**Comment by Mr-Lizard** [comment]
Alrighty, this is available for your testing pleasure.

The first time, to add my tap:

**brew tap Mr-Lizard/homebrew-tap**

Thereafter :

**brew install cfn-nag**

and even:

**brew test cfn-nag**

**Comment by jesseadams** [comment]
@Mr-Lizard Thanks for this work. I am having issues on my machine locally with these instructions but I am guessing it has something to do with paths and rbenv. I'll take a closer look soon.

**Comment by Mr-Lizard** [comment]
No problem @jesseadams.  If your homebrew install is old, you may want to completely uninstall and reinstall it - mine was quite buggy until I did that.

**Comment by Mr-Lizard** [comment]
I should note that the formula name is 'cfn-nag', however the executables are still underscored, 'cfn_nag' !

**Comment by twellspring** [comment]
@jesseadams  I just ran the above instructions and the worked correctly. 
Mojave 10.14.5 
Homebrew 2.1.6

I did the install on both the default OS ruby and 2.6
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by Mr-Lizard** [comment]
Thank you, Mr. Wells !

**Comment by Mr-Lizard** [comment]
After doing some further research, using a subdirectory of this repo for a homebrew repo doesn't seem to be possible.   So...there are 2 options:

1)  Create a repository for Stelligents own homebrew formulae.  It should begin with 'homebrew-', usually the convention is 'homebrew-taps'

2) Go for the throat and submit it (via PR) to homebrew.  I would be happy to handle this.

I recommend using both, starting with 1 before going for an official homebrew formula submission.  Gentlemen, what is your bidding ?

**Comment by oshaughnessy** [comment]
Ooh, good insight! We do have https://github.com/stelligent/homebrew-tap set up for this. Looks like we're using it for `mu` and `config-lint` already.

**Comment by Mr-Lizard** [comment]
There should be an icon for embarrassment !  My apologies !

**Comment by oshaughnessy** [comment]
No, not at all. Glad you brought it up, because I forgot it was there until you mentioned it. Do you have access to submit a PR to that repo instead?

**Comment by Mr-Lizard** [comment]
Not sure, I would have what any lizard off the street would have.

**Comment by oshaughnessy** [comment]
Looks like it's public. I _think_ you'd be good to go.

**Comment by Mr-Lizard** [comment]
Thanks, I couldn't create a branch, so I forked it.  Will be submitting a
PR Real Soon Now.

**Comment by Mr-Lizard** [comment]
A PR has been submitted to [https://github.com/stelligent/homebrew-tap ](url) .

**Comment by twellspring** [comment]
Here is the PR:  https://github.com/stelligent/homebrew-tap/pull/1

**Comment by twellspring** [comment]
PR is merged and the following now works for MacOS and Ubuntu (tested on Bionic)

```
brew tap stelligent/homebrew-tap
brew install cfn-nag
```

It is currently on v0.4.33
Working on a process for keeping brew up to date.
